/// This code was autogenerated
import 'package:built_value/built_value.dart';
import 'bookmark_field_item.dart';

class AlternateStateData {
  /// Name of the alternate state.
  /// Default is current selections: $
  /// Original name: qStateName
  String stateName;
  /// List of the selections.
  /// Original name: qFieldItems
  null fieldItems;
}

