/// This code was autogenerated
//import 'package:built_value/built_value.dart';
import 'nx_meta.dart';

class AppScript {
  /// Script text.
  /// Original name: qScript
  String script;
  /// Information about publishing and permissions.
  /// This parameter is optional.
  /// Original name: qMeta
  NxMeta meta;
}

