/// This code was autogenerated
import 'package:built_value/built_value.dart';
import 'nx_cell.dart';

/// Lists the app objects. Is the layout for _AppObjectListDef_.
/// <div class=note>An app object is a generic object created at app level.</div>
class AppObjectList {
  /// Information about the list of dimensions.
  /// Original name: qItems
  List<NxCell> items;
}

