/// This file was autogenerated

library array_of_nx_value_point;

import 'package:built_value/serializer.dart';
import 'package:built_value/built_value.dart';
part 'array_of_nx_value_point.g.dart';

abstract class ArrayOfNxValuePoint implements Built<ArrayOfNxValuePoint, ArrayOfNxValuePointBuilder> {

 static Serializer<ArrayOfNxValuePoint> get serializer => _$arrayOfNxValuePointSerializer;

  factory ArrayOfNxValuePoint([updates(ArrayOfNxValuePointBuilder b)]) = _$ArrayOfNxValuePoint;

  ArrayOfNxValuePoint._();
}
