/// This code was autogenerated
import 'package:built_value/built_value.dart';
import 'nx_container_entry.dart';

/// Lists the bookmarks. Is the layout for _BookmarkListDef_.
class BookmarkList {
  /// Information about the list of bookmarks.
  /// Original name: qItems
  null items;
}

