/// This code was autogenerated
import 'package:built_value/built_value.dart';
import 'package:built_value/json_object.dart';

/// Defines the list of bookmarks.
class BookmarkListDef {
  /// Type of the list.
  /// Original name: qType
  String type;
  /// Data
  /// Original name: qData
  JsonObject data;
}

