/// This file was autogenerated

library calendar_strings;

import 'package:built_value/serializer.dart';
import 'package:built_value/built_value.dart';
import 'nx_cell.dart';
import 'package:built_collection/built_collection.dart';
part 'calendar_strings.g.dart';

abstract class CalendarStrings implements Built<CalendarStrings, CalendarStringsBuilder> {

 static Serializer<CalendarStrings> get serializer => _$calendarStringsSerializer;

  /// List of short day names.
  /// Original name: qDayNames
  @nullable
  BuiltList<NxCell> get dayNames;

  /// List of short month names.
  /// Original name: qMonthNames
  @nullable
  BuiltList<NxCell> get monthNames;

  /// List of long day names.
  /// Original name: qLongDayNames
  @nullable
  BuiltList<NxCell> get longDayNames;

  /// List of long month names.
  /// Original name: qLongMonthNames
  @nullable
  BuiltList<NxCell> get longMonthNames;

  factory CalendarStrings([updates(CalendarStringsBuilder b)]) = _$CalendarStrings;

  CalendarStrings._();
}
