/// This code was autogenerated
import 'package:built_value/built_value.dart';


class CalendarStrings {
  /// List of short day names.
  /// Original name: qDayNames
  null dayNames;
  /// List of short month names.
  /// Original name: qMonthNames
  null monthNames;
  /// List of long day names.
  /// Original name: qLongDayNames
  null longDayNames;
  /// List of long month names.
  /// Original name: qLongMonthNames
  null longMonthNames;
}

