/// This code was autogenerated
import 'package:built_value/built_value.dart';
import 'nx_cell.dart';

class CalendarStrings {
  /// List of short day names.
  /// Original name: qDayNames
  List<NxCell> dayNames;
  /// List of short month names.
  /// Original name: qMonthNames
  List<NxCell> monthNames;
  /// List of long day names.
  /// Original name: qLongDayNames
  List<NxCell> longDayNames;
  /// List of long month names.
  /// Original name: qLongMonthNames
  List<NxCell> longMonthNames;
}

