/// This code was autogenerated
//import 'package:built_value/built_value.dart';
import 'package:built_value/json_object.dart';

/// Defines the list of children of a generic object.
/// What is defined in _ChildListDef_ has an impact on what the _GetLayout_ method returns. See _Example_ for more information.
class ChildListDef {
  /// Data that you want to include in the child list definition.
  /// You need to enter the paths to the information you want to retrieve.
  /// Original name: qData
  JsonObject data;
}

