/// This code was autogenerated
import 'package:built_value/built_value.dart';
import 'content_library_list_item.dart';

class ContentLibraryList {
  /// Information about the content library.
  List<ContentLibraryListItem> items;
}

