/// This code was autogenerated
import 'package:built_value/built_value.dart';


class CustomConnector {
  /// Name of the custom connector file.
  String provider;
  /// Name of the parent folder that contains the custom connector file.
  String parent;
  /// Name of the custom connector as displayed in the Qlik interface.
  String displayName;
  /// Mode of the machine (64 or 32 bits).
  /// 
  /// One of:
  /// * CONNECT_DEFAULT
  /// * CONNECT_64
  /// * CONNECT_32
  String machineMode;
  bool supportFileStreaming;
}

