/// This code was autogenerated
//import 'package:built_value/built_value.dart';
import 'nx_cell.dart';

class DataTableEx {
  /// Name of the table.
  /// Original name: qName
  String name;
  /// List of the fields in the table.
  /// Original name: qFields
  List<NxCell> fields;
  /// List of format specification items, within brackets.
  /// Examples of specification items:
  /// * file type
  /// * embedded labels, no labels
  /// * table is &lt;table name&gt;
  /// Original name: qFormatSpec
  String formatSpec;
}

