/// This code was autogenerated
import 'package:built_value/built_value.dart';


class DatabaseInfo {
  /// Name of the product accessed by the provider.
  String dBMSName;
  /// If set to true, it means that the data source contains some databases.
  bool dBUsage;
  /// If set to true, it means that the data source contains some owners.
  bool ownerUsage;
  /// Character string used after the database name.
  /// Example with separator " **.** ":
  /// FROM LinkedTablesData.dbo.Months
  /// Where:
  /// * **LinkedTablesData** is the database name
  /// * **dbo** is the owner name
  /// * **Months** is the table name
  String dBSeparator;
  /// Character string used after the owner name.
  /// Example with separator " **.** ":
  /// FROM LinkedTablesData.dbo.Months
  /// Where:
  /// * **LinkedTablesData** is the database name
  /// * **dbo** is the owner name
  /// * **Months** is the table name
  String ownerSeparator;
  /// If set to true, it means that the database is displayed first, before the owners and tables.
  bool dBFirst;
  /// Prefix used with field, database or owner names that contain special characters or keywords.
  String quotePreffix;
  /// Suffix used with field, database or owner names that contain special characters or keywords.
  String quoteSuffix;
  /// List of the special characters.
  String specialChars;
  /// Name of the default database.
  String defaultDatabase;
  /// List of the script keywords.
  List<String> keywords;
}

