/// This code was autogenerated
import 'package:built_value/built_value.dart';


class DataTable {
  /// Name of the table.
  String name;
  /// Type of the table.
  /// For example: Table or View.
  String type;
}

