/// This code was autogenerated
//import 'package:built_value/built_value.dart';
import 'nx_cell.dart';

/// Lists the dimensions. Is the layout for _DimensionListDef_.
class DimensionList {
  /// Information about the list of dimensions.
  /// Original name: qItems
  List<NxCell> items;
}

