/// This code was autogenerated
import 'package:built_value/built_value.dart';
import 'nx_container_entry.dart';

/// Lists the dimensions. Is the layout for _DimensionListDef_.
class DimensionList {
  /// Information about the list of dimensions.
  List<NxContainerEntry> items;
}

