/// This code was autogenerated
//import 'package:built_value/built_value.dart';


class DoReloadExParams {
  /// Original name: qMode
  int mode;
  /// Original name: qPartial
  bool partial;
  /// Original name: qDebug
  bool debug;
}

