/// This code was autogenerated
//import 'package:built_value/built_value.dart';


/// Defines the embedded snapshot in a generic object.
/// 
/// ### Properties
/// "EmbeddedSnapshotDef": {}
class EmbeddedSnapshotDef {
}

