/// This file was autogenerated

library embedded_snapshot_def;

import 'package:built_value/serializer.dart';
import 'package:built_value/built_value.dart';
part 'embedded_snapshot_def.g.dart';

/// Defines the embedded snapshot in a generic object.
/// 
/// ### Properties
/// "EmbeddedSnapshotDef": {}
abstract class EmbeddedSnapshotDef implements Built<EmbeddedSnapshotDef, EmbeddedSnapshotDefBuilder> {

 static Serializer<EmbeddedSnapshotDef> get serializer => _$embeddedSnapshotDefSerializer;

  factory EmbeddedSnapshotDef([updates(EmbeddedSnapshotDefBuilder b)]) = _$EmbeddedSnapshotDef;

  EmbeddedSnapshotDef._();
}
