/// This code was autogenerated
//import 'package:built_value/built_value.dart';


/// Renders the embedded snapshot in an object.
/// The following is returned:
/// * Any dynamic properties defined in the bookmark
/// * Any properties defined in _qEmbeddedSnapshot_
/// 
/// ### Properties
/// "qEmbeddedSnapshot": {}
class EmbeddedSnapshot {
}

