/// This code was autogenerated
import 'package:built_value/built_value.dart';
import 'progress_message.dart';

class ErrorData {
  /// Detailed information about the error message.
  /// Original name: qErrorString
  String errorString;
  /// Line termination characters.
  /// Original name: qLineEnd
  String lineEnd;
  /// Script statement where the error occurs.
  /// Original name: qLine
  String line;
  /// Type of the error messages.
  /// 
  /// One of:
  /// * EDC_ERROR
  /// * EDC_WARNING
  /// * EDC_CIRCULAR_REFERENCE
  /// Original name: qErrorDataCode
  String errorDataCode;
  /// Original name: qMessage
  ProgressMessage message;
}

