/// This file was autogenerated

library extension_list;

import 'package:built_value/serializer.dart';
import 'package:built_value/built_value.dart';
import 'nx_cell.dart';
import 'package:built_collection/built_collection.dart';
part 'extension_list.g.dart';

abstract class ExtensionList implements Built<ExtensionList, ExtensionListBuilder> {

 static Serializer<ExtensionList> get serializer => _$extensionListSerializer;

  /// Original name: qItems
  @nullable
  BuiltList<NxCell> get items;

  factory ExtensionList([updates(ExtensionListBuilder b)]) = _$ExtensionList;

  ExtensionList._();
}
