/// This file was autogenerated

library field_in_table_data;

import 'package:built_value/serializer.dart';
import 'package:built_value/built_value.dart';
import 'nx_cell.dart';
import 'package:built_collection/built_collection.dart';
part 'field_in_table_data.g.dart';

abstract class FieldInTableData implements Built<FieldInTableData, FieldInTableDataBuilder> {

 static Serializer<FieldInTableData> get serializer => _$fieldInTableDataSerializer;

  /// Name of the field.
  /// Original name: qName
  @nullable
  String get name;

  /// Is shown for fixed records.
  /// _qOriginalFieldName_ and _qName_ are identical if no field names are used in the file.
  /// _qOriginalFieldName_ differs from _qName_ if embedded file names are used in the file.
  /// Original name: qOriginalFields
  @nullable
  BuiltList<NxCell> get originalFields;

  /// Original name: qPresent
  @nullable
  bool get present;

  /// This property is set to true if the field contains some Null values.
  /// Original name: qHasNull
  @nullable
  bool get hasNull;

  /// Original name: qHasWild
  @nullable
  bool get hasWild;

  /// This property is set to true if the field contains some duplicate values.
  /// Original name: qHasDuplicates
  @nullable
  bool get hasDuplicates;

  /// This property is set to true if the field contains a synthetic key.
  /// Original name: qIsSynthetic
  @nullable
  bool get isSynthetic;

  /// Number of records that have values (for example, not NULL) in the field as compared to the total number of records in the table.
  /// Original name: qInformationDensity
  @nullable
  num get informationDensity;

  /// Number of values that are non Null.
  /// Original name: qnNonNulls
  @nullable
  int get nNonNulls;

  /// Number of rows in the field.
  /// Original name: qnRows
  @nullable
  int get nRows;

  /// Number of distinct values in the field (in the current table) as compared to the total number of distinct values of this field (in all tables).
  /// Original name: qSubsetRatio
  @nullable
  num get subsetRatio;

  /// Number of distinct values in the field.
  /// Original name: qnTotalDistinctValues
  @nullable
  int get nTotalDistinctValues;

  /// Original name: qnPresentDistinctValues
  @nullable
  int get nPresentDistinctValues;

  /// Tells if the field is a key field.
  /// 
  /// One of:
  /// * NOT_KEY
  /// * ANY_KEY
  /// * PRIMARY_KEY
  /// * PERFECT_KEY
  /// Original name: qKeyType
  @nullable
  String get keyType;

  /// Comment related to the field.
  /// Original name: qComment
  @nullable
  String get comment;

  /// List of tags related to the field.
  /// Original name: qTags
  @nullable
  BuiltList<NxCell> get tags;

  /// List of the derived fields.
  /// Original name: qDerivedFields
  @nullable
  BuiltList<NxCell> get derivedFields;

  /// Original name: qIsFieldOnTheFly
  @nullable
  bool get isFieldOnTheFly;

  /// Original name: qReadableName
  @nullable
  String get readableName;

  factory FieldInTableData([updates(FieldInTableDataBuilder b)]) = _$FieldInTableData;

  FieldInTableData._();
}
