/// This code was autogenerated
import 'package:built_value/built_value.dart';


class FieldValue {
  /// Text related to the field value.
  /// This parameter is optional.
  /// Original name: qText
  String text;
  /// Is set to true if the value is a numeric.
  /// This parameter is optional. Default is false.
  /// Original name: qIsNumeric
  bool isNumeric;
  /// Numeric value of the field.
  /// This parameter is displayed if _qIsNumeric_ is set to true.
  /// This parameter is optional.
  /// Original name: qNumber
  num number;
}

