/// This file was autogenerated

library field_value;

import 'package:built_value/serializer.dart';
import 'package:built_value/built_value.dart';
part 'field_value.g.dart';

abstract class FieldValue implements Built<FieldValue, FieldValueBuilder> {
  static Serializer<FieldValue> get serializer => _$fieldValueSerializer;

  /// Text related to the field value.
  /// This parameter is optional.
  /// Original name: qText
  @nullable
  String get text;

  /// Is set to true if the value is a numeric.
  /// This parameter is optional. Default is false.
  /// Original name: qIsNumeric
  @nullable
  bool get isNumeric;

  /// Numeric value of the field.
  /// This parameter is displayed if _qIsNumeric_ is set to true.
  /// This parameter is optional.
  /// Original name: qNumber
  @nullable
  num get number;

  factory FieldValue([updates(FieldValueBuilder b)]) = _$FieldValue;

  factory FieldValue.init({String text, bool isNumeric, num number}) =
      _$FieldValue._;

  FieldValue._();
}
