/// This code was autogenerated
import 'package:built_value/built_value.dart';
import 'nx_info.dart';
import 'package:built_value/json_object.dart';

class GenericObjectProperties {
  /// Identifier and type of the object.
  /// This parameter is mandatory.
  /// Original name: qInfo
  NxInfo info;
  /// Should be set to create an object that is linked to another object. Enter the identifier of the linking object (i.e the object you want to link to).
  /// This parameter is mandatory.
  /// If you do not want to link your object, set this parameter to an empty string.
  /// Original name: qExtendsId
  String extendsId;
  /// Definition of the dynamic properties.
  /// Original name: qMetaDef
  JsonObject metaDef;
}

