/// This code was autogenerated
//import 'package:built_value/built_value.dart';
import 'nx_info.dart';
import 'nx_library_measure_def.dart';
import 'package:built_value/json_object.dart';

class GenericMeasureProperties {
  /// Information about the measure.
  /// This parameter is mandatory.
  /// Original name: qInfo
  NxInfo info;
  /// Definition of the measure.
  /// This parameter is mandatory.
  /// Original name: qMeasure
  NxLibraryMeasureDef measure;
  /// Definition of the dynamic properties.
  /// Original name: qMetaDef
  JsonObject metaDef;
}

