/// This code was autogenerated
import 'package:built_value/built_value.dart';
import 'generic_object_properties.dart';
import 'generic_object_entry.dart';
import 'generic_bookmark_entry.dart';

class GenericObjectEntry {
  /// Information about the generic object properties.
  /// Original name: qProperty
  GenericObjectProperties property;
  /// Information about the children of the generic object.
  /// Original name: qChildren
  null children;
  /// Reference to a bookmark/snapshot that is embedded in the generic object.
  /// Original name: qEmbeddedSnapshotRef
  GenericBookmarkEntry embeddedSnapshotRef;
}

