/// This code was autogenerated
//import 'package:built_value/built_value.dart';
import 'generic_bookmark_properties.dart';
import 'nx_bookmark.dart';

class GenericBookmarkEntry {
  /// Information about the properties of the bookmark.
  /// Original name: qProperties
  GenericBookmarkProperties properties;
  /// Information about the bookmark.
  /// Original name: qBookmark
  NxBookmark bookmark;
}

