/// This file was autogenerated

library generic_measure_layout;

import 'package:built_value/serializer.dart';
import 'package:built_value/built_value.dart';
import 'nx_info.dart';
import 'nx_library_measure.dart';
import 'nx_meta.dart';
part 'generic_measure_layout.g.dart';

/// Is the layout for _GenericMeasureProperties_.
abstract class GenericMeasureLayout
    implements Built<GenericMeasureLayout, GenericMeasureLayoutBuilder> {
  static Serializer<GenericMeasureLayout> get serializer =>
      _$genericMeasureLayoutSerializer;

  /// Information about the object.
  /// Original name: qInfo
  @nullable
  NxInfo get info;

  /// Information about the measure.
  /// Original name: qMeasure
  @nullable
  NxLibraryMeasure get measure;

  /// Information on publishing and permissions.
  /// Original name: qMeta
  @nullable
  NxMeta get meta;

  factory GenericMeasureLayout([updates(GenericMeasureLayoutBuilder b)]) =
      _$GenericMeasureLayout;

  factory GenericMeasureLayout.init(
      {NxInfo info,
      NxLibraryMeasure measure,
      NxMeta meta}) = _$GenericMeasureLayout._;

  GenericMeasureLayout._();
}
