/// This file was autogenerated

library generic_dimension_layout;

import 'package:built_value/serializer.dart';
import 'package:built_value/built_value.dart';
import 'nx_info.dart';
import 'nx_meta.dart';
import 'nx_library_dimension.dart';
import 'nx_cell.dart';
import 'package:built_collection/built_collection.dart';
part 'generic_dimension_layout.g.dart';

/// Is the layout for _GenericDimensionProperties_.
abstract class GenericDimensionLayout implements Built<GenericDimensionLayout, GenericDimensionLayoutBuilder> {

 static Serializer<GenericDimensionLayout> get serializer => _$genericDimensionLayoutSerializer;

  /// Identifier and type of the dimension.
  /// Original name: qInfo
  @nullable
  NxInfo get info;

  /// Information about publishing and permissions.
  /// Original name: qMeta
  @nullable
  NxMeta get meta;

  /// Name and label of the dimension, information about grouping.
  /// Original name: qDim
  @nullable
  NxLibraryDimension get dim;

  /// Cardinal and tags related to the dimension.
  /// Length of the longest value in the field.
  /// Original name: qDimInfos
  @nullable
  List<NxCell> get dimInfos;

  factory GenericDimensionLayout([updates(GenericDimensionLayoutBuilder b)]) = _$GenericDimensionLayout;

  GenericDimensionLayout._();
}
