/// This code was autogenerated
import 'package:built_value/built_value.dart';
import 'nx_info.dart';
import 'nx_meta_def.dart';

class GenericBookmarkProperties {
  /// Information about the bookmark.
  /// This parameter is mandatory.
  NxInfo info;
  /// Definition of the dynamic properties.
  NxMetaDef metaDef;
}

