/// This code was autogenerated
//import 'package:built_value/built_value.dart';
import 'nx_info.dart';
import 'nx_meta.dart';
import 'nx_library_dimension.dart';
import 'nx_cell.dart';

/// Is the layout for _GenericDimensionProperties_.
class GenericDimensionLayout {
  /// Identifier and type of the dimension.
  /// Original name: qInfo
  NxInfo info;
  /// Information about publishing and permissions.
  /// Original name: qMeta
  NxMeta meta;
  /// Name and label of the dimension, information about grouping.
  /// Original name: qDim
  NxLibraryDimension dim;
  /// Cardinal and tags related to the dimension.
  /// Length of the longest value in the field.
  /// Original name: qDimInfos
  List<NxCell> dimInfos;
}

