/// This code was autogenerated
import 'package:built_value/built_value.dart';
import 'nx_info.dart';
import 'package:built_value/json_object.dart';

class GenericBookmarkProperties {
  /// Information about the bookmark.
  /// This parameter is mandatory.
  /// Original name: qInfo
  NxInfo info;
  /// Definition of the dynamic properties.
  /// Original name: qMetaDef
  JsonObject metaDef;
}

