/// This code was autogenerated
//import 'package:built_value/built_value.dart';
import 'nx_info.dart';
import 'nx_meta.dart';
import 'nx_bookmark.dart';
import 'nx_cell.dart';

/// Is the layout for _GenericBookmarkProperties_.
class GenericBookmarkLayout {
  /// Information about the object.
  /// Original name: qInfo
  NxInfo info;
  /// Information on publishing and permissions.
  /// Original name: qMeta
  NxMeta meta;
  /// Information about the bookmark.
  /// Original name: qBookmark
  NxBookmark bookmark;
  /// Original name: qFieldInfos
  List<NxCell> fieldInfos;
}

