/// This file was autogenerated

library list_object;

import 'package:built_value/serializer.dart';
import 'package:built_value/built_value.dart';
import 'size.dart';
import 'nx_validation_error.dart';
import 'nx_dimension_info.dart';
import 'nx_cell.dart';
import 'package:built_collection/built_collection.dart';
part 'list_object.g.dart';

/// Renders the properties of a list object. Is the layout for _ListObjectDef_.
/// For more information about the definition of a list object, see _Generic object_.
/// <div class=note>ListObject is used by the _GetLayout Method_ to display the properties of a list object. </div>
abstract class ListObject implements Built<ListObject, ListObjectBuilder> {

 static Serializer<ListObject> get serializer => _$listObjectSerializer;

  /// Name of the alternate state.
  /// Default is current selections _$_ .
  /// Original name: qStateName
  @nullable
  String get stateName;

  /// Defines the size of a list object.
  /// Original name: qSize
  @nullable
  Size get size;

  /// This parameter is optional and is displayed in case of error.
  /// Original name: qError
  @nullable
  NxValidationError get error;

  /// Information about the dimension.
  /// Original name: qDimensionInfo
  @nullable
  NxDimensionInfo get dimensionInfo;

  /// Lists the expressions in the list object.
  /// Original name: qExpressions
  @nullable
  BuiltList<NxCell> get expressions;

  /// Set of data.
  /// Is empty if nothing has been defined in **qInitialDataFetch** in _ListObjectDef_.
  /// Original name: qDataPages
  @nullable
  BuiltList<NxCell> get dataPages;

  factory ListObject([updates(ListObjectBuilder b)]) = _$ListObject;

  factory ListObject.init({String stateName, Size size, NxValidationError error, NxDimensionInfo dimensionInfo, BuiltList<NxCell> expressions, BuiltList<NxCell> dataPages}) = _$ListObject._;

  ListObject._();
}
