/// This code was autogenerated
import 'package:built_value/built_value.dart';


/// Defines the list of media files.
/// <div class=note>This struct is deprecated.</div>
/// 
/// ### Properties
/// "qMediaListDef": {}
/// _qMediaListDef_ has an empty structure. No properties need to be set.
class MediaListDef {
}

