/// This code was autogenerated
import 'package:built_value/built_value.dart';


/// Layout for _NxAttrExprDef_.
class NxAttrExprInfo {
  /// Minimum value.
  /// Original name: qMin
  num min;
  /// Maximum value.
  /// Original name: qMax
  num max;
  /// Original name: qFallbackTitle
  String fallbackTitle;
  /// String version of the minimum Value.
  /// Original name: qMinText
  String minText;
  /// String version of the maximum Value.
  /// Original name: qMaxText
  String maxText;
}

