/// This file was autogenerated

library nx_attribute_dim_values;

import 'package:built_value/serializer.dart';
import 'package:built_value/built_value.dart';
import 'nx_cell.dart';
import 'package:built_collection/built_collection.dart';
part 'nx_attribute_dim_values.g.dart';

abstract class NxAttributeDimValues implements Built<NxAttributeDimValues, NxAttributeDimValuesBuilder> {

 static Serializer<NxAttributeDimValues> get serializer => _$nxAttributeDimValuesSerializer;

  /// List of values.
  /// Original name: qValues
  @nullable
  BuiltList<NxCell> get values;

  factory NxAttributeDimValues([updates(NxAttributeDimValuesBuilder b)]) = _$NxAttributeDimValues;

  NxAttributeDimValues._();
}
