/// This code was autogenerated
import 'package:built_value/built_value.dart';
import 'nx_tick_cell.dart';

class NxAxisTicks {
  /// Name of the derived definition.
  /// Original name: qName
  String name;
  /// List of tags.
  /// Original name: qTags
  null tags;
  /// List of ticks.
  /// Original name: qTicks
  null ticks;
}

