/// This file was autogenerated

library nx_axis_data;

import 'package:built_value/serializer.dart';
import 'package:built_value/built_value.dart';
import 'nx_cell.dart';
import 'package:built_collection/built_collection.dart';
part 'nx_axis_data.g.dart';

abstract class NxAxisData implements Built<NxAxisData, NxAxisDataBuilder> {

 static Serializer<NxAxisData> get serializer => _$nxAxisDataSerializer;

  /// List of axis data.
  /// Original name: qAxis
  @nullable
  BuiltList<NxCell> get axis;

  factory NxAxisData([updates(NxAxisDataBuilder b)]) = _$NxAxisData;

  factory NxAxisData.init({BuiltList<NxCell> axis}) = _$NxAxisData._;

  NxAxisData._();
}
