/// This file was autogenerated

library nx_axis_ticks;

import 'package:built_value/serializer.dart';
import 'package:built_value/built_value.dart';
import 'nx_cell.dart';
import 'package:built_collection/built_collection.dart';
part 'nx_axis_ticks.g.dart';

abstract class NxAxisTicks implements Built<NxAxisTicks, NxAxisTicksBuilder> {

 static Serializer<NxAxisTicks> get serializer => _$nxAxisTicksSerializer;

  /// Name of the derived definition.
  /// Original name: qName
  @nullable
  String get name;

  /// List of tags.
  /// Original name: qTags
  @nullable
  BuiltList<NxCell> get tags;

  /// List of ticks.
  /// Original name: qTicks
  @nullable
  BuiltList<NxCell> get ticks;

  factory NxAxisTicks([updates(NxAxisTicksBuilder b)]) = _$NxAxisTicks;

  factory NxAxisTicks.init({String name, BuiltList<NxCell> tags, BuiltList<NxCell> ticks}) = _$NxAxisTicks._;

  NxAxisTicks._();
}
