/// This file was autogenerated

library nx_attr_expr_info;

import 'package:built_value/serializer.dart';
import 'package:built_value/built_value.dart';
part 'nx_attr_expr_info.g.dart';

/// Layout for _NxAttrExprDef_.
abstract class NxAttrExprInfo implements Built<NxAttrExprInfo, NxAttrExprInfoBuilder> {

 static Serializer<NxAttrExprInfo> get serializer => _$nxAttrExprInfoSerializer;

  /// Minimum value.
  /// Original name: qMin
  @nullable
  num get min;

  /// Maximum value.
  /// Original name: qMax
  @nullable
  num get max;

  /// Original name: qFallbackTitle
  @nullable
  String get fallbackTitle;

  /// String version of the minimum Value.
  /// Original name: qMinText
  @nullable
  String get minText;

  /// String version of the maximum Value.
  /// Original name: qMaxText
  @nullable
  String get maxText;

  factory NxAttrExprInfo([updates(NxAttrExprInfoBuilder b)]) = _$NxAttrExprInfo;

  NxAttrExprInfo._();
}
