/// This code was autogenerated
import 'package:built_value/built_value.dart';
import 'nx_cell.dart';

class NxAttributeDimValues {
  /// List of values.
  /// Original name: qValues
  List<NxCell> values;
}

