/// This code was autogenerated
import 'package:built_value/built_value.dart';
import 'nx_meta.dart';
import 'locale_info.dart';
import 'static_content_url.dart';

/// ### Qlik Sense Desktop
/// In Qlik Sense Desktop, this structure can contain dynamic properties.
/// 
/// ### Qlik Sense Enterprise
/// In Qlik Sense Enterprise, only a few dynamic properties at the app level are persisted.
/// The persisted dynamic properties are the following:
/// * modifiedDate
/// * published
/// * publishTime
/// * privileges
/// * description
/// * dynamicColor
class NxAppLayout {
  /// Title of the app.
  String title;
  /// In Qlik Sense Enterprise, this property corresponds to the app identifier (GUID).
  /// In Qlik Sense Desktop, this property corresponds to the full path of the app.
  String fileName;
  /// Date and time of the last reload of the app in ISO format.
  String lastReloadTime;
  /// Is set to true if the app has been updated since the last save.
  bool modified;
  /// Is set to true if a script is defined in the app.
  bool hasScript;
  /// Array of alternate states.
  List<String> stateNames;
  /// Information on publishing and permissions.
  NxMeta meta;
  /// Information about the locale.
  LocaleInfo localeInfo;
  /// Is set to true if the app contains data following a script reload.
  bool hasData;
  /// If set to true, it means that the app is read-only.
  bool readOnly;
  /// If set to true, it means that the app was opened without loading its data.
  bool isOpenedWithoutData;
  /// App thumbnail.
  StaticContentUrl thumbnail;
}

