/// This file was autogenerated

library nx_calc_cond;

import 'package:built_value/serializer.dart';
import 'package:built_value/built_value.dart';
import 'value_expr.dart';
import 'string_expr.dart';
part 'nx_calc_cond.g.dart';

abstract class NxCalcCond implements Built<NxCalcCond, NxCalcCondBuilder> {

 static Serializer<NxCalcCond> get serializer => _$nxCalcCondSerializer;

  /// Condition for calculating an hypercube, dimension or measure.
  /// Original name: qCond
  @nullable
  ValueExpr get cond;

  /// Evaluated if Cond is not fullfilled.
  /// Original name: qMsg
  @nullable
  StringExpr get msg;

  factory NxCalcCond([updates(NxCalcCondBuilder b)]) = _$NxCalcCond;

  factory NxCalcCond.init({ValueExpr cond, StringExpr msg}) = _$NxCalcCond._;

  NxCalcCond._();
}
