/// This file was autogenerated

library nx_cell_position;

import 'package:built_value/serializer.dart';
import 'package:built_value/built_value.dart';
part 'nx_cell_position.g.dart';

abstract class NxCellPosition implements Built<NxCellPosition, NxCellPositionBuilder> {

 static Serializer<NxCellPosition> get serializer => _$nxCellPositionSerializer;

  /// Position of the cell on the x-axis.
  /// Original name: qx
  @nullable
  int get x;

  /// Position of the cell on the y-axis.
  /// Original name: qy
  @nullable
  int get y;

  factory NxCellPosition([updates(NxCellPositionBuilder b)]) = _$NxCellPosition;

  factory NxCellPosition.init({int x, int y}) = _$NxCellPosition._;

  NxCellPosition._();
}
