/// This code was autogenerated
import 'package:built_value/built_value.dart';
import 'nx_info.dart';
import 'nx_meta.dart';
import 'package:built_value/json_object.dart';

class NxContainerEntry {
  /// Information about the object.
  NxInfo info;
  /// Information on publishing and permissions.
  NxMeta meta;
  /// Set of data.
  JsonObject data;
}

