/// This code was autogenerated
import 'package:built_value/built_value.dart';
import 'nx_highlight_ranges.dart';
import 'nx_attribute_expression_values.dart';
import 'nx_attribute_dim_values.dart';

class NxCell {
  /// Some text.
  /// This parameter is optional.
  String text;
  /// A value.
  /// This parameter is optional.
  num num;
  /// Rank number of the value, starting from 0.
  /// If the element number is a negative number, it means that the returned value is not an element number.
  /// You can get the following negative values:
  /// * -1: the cell is a _Total_ cell. It shows a total.
  /// * -2: the cell is collapsed. Applies to pivot tables.
  /// * -3: the cell belongs to the group _Others_ .
  /// * -4: the cell is empty. Applies to pivot tables.
  int elemNumber;
  /// State of the value.
  /// The default state for a measure is L.
  /// 
  /// One of:
  /// * L or LOCKED
  /// * S or SELECTED
  /// * O or OPTION
  /// * D or DESELECTED
  /// * A or ALTERNATIVE
  /// * X or EXCLUDED
  /// * XS or EXCL_SELECTED
  /// * XL or EXCL_LOCKED
  /// * NSTATES
  String state;
  /// Is set to _true_ , if **qText** and **qNum** are empty.
  /// This parameter is optional. The default value is _false_ .
  bool isEmpty;
  /// Is set to _true_ if a total is displayed in the cell.
  /// This parameter is optional. The default value is _false_ .
  /// Not applicable to list objects.
  bool isTotalCell;
  /// Is set to _true_ if the cell belongs to the group _Others_ .
  /// Dimension values can be set as _Others_ depending on what has been defined in **OtherTotalSpecProp** .
  /// This parameter is optional. The default value is _false_ .
  /// Not applicable to list objects.
  bool isOtherCell;
  /// Frequency of the value.
  /// This parameter is optional.
  String frequency;
  /// Search hits.
  /// The search hits are highlighted.
  /// This parameter is optional.
  NxHighlightRanges highlightRanges;
  /// Attribute expression values.
  NxAttributeExpressionValues attrExps;
  /// Attribute dimensions values.
  NxAttributeDimValues attrDims;
  /// Is set to _true_ if the value is Null.
  bool isNull;
}

