/// This code was autogenerated
import 'package:built_value/built_value.dart';


class NxContinuousDataOptions {
  /// Start value.
  num start;
  /// End value.
  num end;
  /// Number of bins for binning.
  int nbrPoints;
  /// Maximum number of ticks.
  int maxNbrTicks;
  /// Maximum number of lines.
  int maxNumberLines;
}

