/// This code was autogenerated
//import 'package:built_value/built_value.dart';
import 'nx_cell.dart';

class NxDerivedFieldDescriptionList {
  /// Information about the derived fields.
  /// Original name: qDerivedFieldLists
  List<NxCell> derivedFieldLists;
}

