/// This code was autogenerated
import 'package:built_value/built_value.dart';
import 'nx_derived_field.dart';
import 'nx_derived_group.dart';

class NxDerivedFieldsData {
  /// Name of the derived definition.
  /// Original name: qDerivedDefinitionName
  String derivedDefinitionName;
  /// List of the derived fields.
  /// Original name: qFieldDefs
  null fieldDefs;
  /// List of the derived groups.
  /// Original name: qGroupDefs
  null groupDefs;
  /// List of tags on the derived fields.
  /// Original name: qTags
  null tags;
}

