/// This file was autogenerated

library nx_derived_fields_data;

import 'package:built_value/serializer.dart';
import 'package:built_value/built_value.dart';
import 'nx_cell.dart';
import 'package:built_collection/built_collection.dart';
part 'nx_derived_fields_data.g.dart';

abstract class NxDerivedFieldsData implements Built<NxDerivedFieldsData, NxDerivedFieldsDataBuilder> {

 static Serializer<NxDerivedFieldsData> get serializer => _$nxDerivedFieldsDataSerializer;

  /// Name of the derived definition.
  /// Original name: qDerivedDefinitionName
  @nullable
  String get derivedDefinitionName;

  /// List of the derived fields.
  /// Original name: qFieldDefs
  @nullable
  List<NxCell> get fieldDefs;

  /// List of the derived groups.
  /// Original name: qGroupDefs
  @nullable
  List<NxCell> get groupDefs;

  /// List of tags on the derived fields.
  /// Original name: qTags
  @nullable
  List<NxCell> get tags;

  factory NxDerivedFieldsData([updates(NxDerivedFieldsDataBuilder b)]) = _$NxDerivedFieldsData;

  NxDerivedFieldsData._();
}
