/// This file was autogenerated

library nx_data_area_page;

import 'package:built_value/serializer.dart';
import 'package:built_value/built_value.dart';
part 'nx_data_area_page.g.dart';

abstract class NxDataAreaPage implements Built<NxDataAreaPage, NxDataAreaPageBuilder> {

 static Serializer<NxDataAreaPage> get serializer => _$nxDataAreaPageSerializer;

  /// Position from the left.
  /// Corresponds to the lowest possible value of the first measure (the measure on the x-axis).
  /// Original name: qLeft
  @nullable
  num get left;

  /// Position from the top.
  /// Corresponds to the highest possible value of the second measure (the measure on the y-axis).
  /// Original name: qTop
  @nullable
  num get top;

  /// Width of the page.
  /// Corresponds to the highest possible value of the first measure (the measure on the x-axis).
  /// Original name: qWidth
  @nullable
  num get width;

  /// Height of the page.
  /// The difference between _qTop_ and _qHeight_ gives the lowest possible value of the second measure (the measure on the y-axis).
  /// Original name: qHeight
  @nullable
  num get height;

  factory NxDataAreaPage([updates(NxDataAreaPageBuilder b)]) = _$NxDataAreaPage;

  NxDataAreaPage._();
}
