/// This file was autogenerated

library nx_field_selection_info;

import 'package:built_value/serializer.dart';
import 'package:built_value/built_value.dart';
part 'nx_field_selection_info.g.dart';

abstract class NxFieldSelectionInfo implements Built<NxFieldSelectionInfo, NxFieldSelectionInfoBuilder> {

 static Serializer<NxFieldSelectionInfo> get serializer => _$nxFieldSelectionInfoSerializer;

  /// Name of the field.
  /// Original name: qName
  @nullable
  String get name;

  /// Selection mode.
  /// ### Properties
  /// One of:
  /// * NORMAL for a selection in normal mode.
  /// * AND for a selection in AND mode.
  /// * NOT for a selection NOT in AND mode.
  /// One of:
  /// * NORMAL or SELECTION_MODE_NORMAL
  /// * AND or SELECTION_MODE_AND
  /// * NOT or SELECTION_MODE_NOT
  /// Original name: qFieldSelectionMode
  @nullable
  String get fieldSelectionMode;

  factory NxFieldSelectionInfo([updates(NxFieldSelectionInfoBuilder b)]) = _$NxFieldSelectionInfo;

  NxFieldSelectionInfo._();
}
