/// This code was autogenerated
import 'package:built_value/built_value.dart';


class NxGroupTail {
  /// Number of elements that are part of the previous tail.
  /// This number depends on the paging, more particularly it depends on the values defined in _qTop_ and _qHeight_ .
  /// Is not shown if the value is 0.
  /// This parameter is optional.
  int up;
  /// Number of elements that are part of the next tail.
  /// This number depends on the paging, more particularly it depends on the values defined in _qTop_ and _qHeight_
  /// Is not shown if the value is 0.
  /// This parameter is optional.
  int down;
}

