/// This code was autogenerated
import 'package:built_value/built_value.dart';
import 'package:built_value/json_object.dart';

class NxGetBookmarkOptions {
  /// List of object types.
  /// Original name: qTypes
  null types;
  /// Set of data.
  /// Original name: qData
  JsonObject data;
}

