/// This code was autogenerated
import 'package:built_value/built_value.dart';
import 'char_range.dart';

class NxHighlightRanges {
  /// Ranges of highlighted values.
  /// Original name: qRanges
  null ranges;
}

