/// This code was autogenerated
import 'package:built_value/built_value.dart';
import 'nx_cell.dart';

class NxHighlightRanges {
  /// Ranges of highlighted values.
  /// Original name: qRanges
  List<NxCell> ranges;
}

