/// This file was autogenerated

library nx_highlight_ranges;

import 'package:built_value/serializer.dart';
import 'package:built_value/built_value.dart';
import 'nx_cell.dart';
import 'package:built_collection/built_collection.dart';
part 'nx_highlight_ranges.g.dart';

abstract class NxHighlightRanges implements Built<NxHighlightRanges, NxHighlightRangesBuilder> {

 static Serializer<NxHighlightRanges> get serializer => _$nxHighlightRangesSerializer;

  /// Ranges of highlighted values.
  /// Original name: qRanges
  @nullable
  List<NxCell> get ranges;

  factory NxHighlightRanges([updates(NxHighlightRangesBuilder b)]) = _$NxHighlightRanges;

  NxHighlightRanges._();
}
