/// This file was autogenerated

library nx_info;

import 'package:built_value/serializer.dart';
import 'package:built_value/built_value.dart';
part 'nx_info.g.dart';

abstract class NxInfo implements Built<NxInfo, NxInfoBuilder> {
  static Serializer<NxInfo> get serializer => _$nxInfoSerializer;

  /// Identifier of the object.
  /// If the chosen identifier is already in use, the engine automatically sets another one.
  /// If an identifier is not set, the engine automatically sets one.
  /// This parameter is optional.
  /// Original name: qId
  @nullable
  String get id;

  /// Type of the object.
  /// This parameter is mandatory.
  /// Original name: qType
  @nullable
  String get type;

  factory NxInfo([updates(NxInfoBuilder b)]) = _$NxInfo;

  factory NxInfo.init({String id, String type}) = _$NxInfo._;

  NxInfo._();
}
