/// This code was autogenerated
import 'package:built_value/built_value.dart';


class NxListObjectExpressionDef {
  /// Value of the expression.
  String expr;
  /// Refers to an expression stored in the library.
  String libraryId;
}

