/// This code was autogenerated
//import 'package:built_value/built_value.dart';
import 'nx_cell.dart';

class NxLibraryDimension {
  /// Information about the grouping.
  /// 
  /// One of:
  /// * N or GRP_NX_NONE
  /// * H or GRP_NX_HIEARCHY
  /// * C or GRP_NX_COLLECTION
  /// Original name: qGrouping
  String grouping;
  /// Array of dimension names.
  /// Original name: qFieldDefs
  List<NxCell> fieldDefs;
  /// Array of dimension labels.
  /// Original name: qFieldLabels
  List<NxCell> fieldLabels;
  /// Original name: qLabelExpression
  String labelExpression;
}

