/// This file was autogenerated

library nx_library_measure;

import 'package:built_value/serializer.dart';
import 'package:built_value/built_value.dart';
import 'nx_cell.dart';
import 'package:built_collection/built_collection.dart';
part 'nx_library_measure.g.dart';

abstract class NxLibraryMeasure implements Built<NxLibraryMeasure, NxLibraryMeasureBuilder> {

 static Serializer<NxLibraryMeasure> get serializer => _$nxLibraryMeasureSerializer;

  /// Original name: qLabel
  @nullable
  String get label;

  /// Original name: qDef
  @nullable
  String get def;

  /// 
  /// One of:
  /// * N or GRP_NX_NONE
  /// * H or GRP_NX_HIEARCHY
  /// * C or GRP_NX_COLLECTION
  /// Original name: qGrouping
  @nullable
  String get grouping;

  /// Original name: qExpressions
  @nullable
  List<NxCell> get expressions;

  /// Original name: qActiveExpression
  @nullable
  int get activeExpression;

  /// Original name: qLabelExpression
  @nullable
  String get labelExpression;

  factory NxLibraryMeasure([updates(NxLibraryMeasureBuilder b)]) = _$NxLibraryMeasure;

  NxLibraryMeasure._();
}
