/// This code was autogenerated
import 'package:built_value/built_value.dart';


class NxListObjectExpressionDef {
  /// Value of the expression.
  /// Original name: qExpr
  String expr;
  /// Refers to an expression stored in the library.
  /// Original name: qLibraryId
  String libraryId;
}

