/// This file was autogenerated

library nx_meta_def;

import 'package:built_value/serializer.dart';
import 'package:built_value/built_value.dart';
part 'nx_meta_def.g.dart';

/// Used to collect meta data.
/// 
/// ### Properties
/// Semantic type with an empty structure.
abstract class NxMetaDef implements Built<NxMetaDef, NxMetaDefBuilder> {

 static Serializer<NxMetaDef> get serializer => _$nxMetaDefSerializer;

  factory NxMetaDef([updates(NxMetaDefBuilder b)]) = _$NxMetaDef;

  NxMetaDef._();
}
