/// This code was autogenerated
//import 'package:built_value/built_value.dart';
import 'nx_cell.dart';

class NxMatchingFieldInfo {
  /// Name of the field.
  /// Original name: qName
  String name;
  /// List of tags.
  /// Original name: qTags
  List<NxCell> tags;
}

