/// This file was autogenerated

library nx_measure_info;

import 'package:built_value/serializer.dart';
import 'package:built_value/built_value.dart';
import 'field_attributes.dart';
import 'nx_validation_error.dart';
import 'nx_cell.dart';
import 'package:built_collection/built_collection.dart';
part 'nx_measure_info.g.dart';

/// Layout for _NxInlineMeasureDef_.
abstract class NxMeasureInfo implements Built<NxMeasureInfo, NxMeasureInfoBuilder> {

 static Serializer<NxMeasureInfo> get serializer => _$nxMeasureInfoSerializer;

  /// Corresponds to the label of the measure.
  /// If the label is not defined then the measure name is used.
  /// Original name: qFallbackTitle
  @nullable
  String get fallbackTitle;

  /// Length of the longest value in the field.
  /// Original name: qApprMaxGlyphCount
  @nullable
  int get apprMaxGlyphCount;

  /// Number of distinct field values.
  /// Original name: qCardinal
  @nullable
  int get cardinal;

  /// Sort indicator.
  /// The default value is no sorting.
  /// This parameter is optional.
  /// 
  /// One of:
  /// * N or NX_SORT_INDICATE_NONE
  /// * A or NX_SORT_INDICATE_ASC
  /// * D or NX_SORT_INDICATE_DESC
  /// Original name: qSortIndicator
  @nullable
  String get sortIndicator;

  /// Format of the field.
  /// This parameter is optional.
  /// Original name: qNumFormat
  @nullable
  FieldAttributes get numFormat;

  /// Lowest value in the range.
  /// Original name: qMin
  @nullable
  num get min;

  /// Highest value in the range.
  /// Original name: qMax
  @nullable
  num get max;

  /// This parameter is optional.
  /// Gives information on the error.
  /// Original name: qError
  @nullable
  NxValidationError get error;

  /// If set to true, it inverts the sort criteria in the field.
  /// Original name: qReverseSort
  @nullable
  bool get reverseSort;

  /// This parameter is set to true if _qNumFormat_ is set to _U_ (unknown). The engine guesses the type of the field based on the field's expression.
  /// Original name: qIsAutoFormat
  @nullable
  bool get isAutoFormat;

  /// List of attribute expressions.
  /// Original name: qAttrExprInfo
  @nullable
  List<NxCell> get attrExprInfo;

  /// List of attribute dimensions.
  /// Original name: qAttrDimInfo
  @nullable
  List<NxCell> get attrDimInfo;

  /// The message displayed if calculation condition is not fulfilled.
  /// Original name: qCalcCondMsg
  @nullable
  String get calcCondMsg;

  factory NxMeasureInfo([updates(NxMeasureInfoBuilder b)]) = _$NxMeasureInfo;

  NxMeasureInfo._();
}
