/// This code was autogenerated
import 'package:built_value/built_value.dart';
import 'field_attributes.dart';
import 'nx_validation_error.dart';
import 'nx_attr_expr_info.dart';
import 'nx_attr_dim_info.dart';

/// Layout for _NxInlineMeasureDef_.
class NxMeasureInfo {
  /// Corresponds to the label of the measure.
  /// If the label is not defined then the measure name is used.
  String fallbackTitle;
  /// Length of the longest value in the field.
  int apprMaxGlyphCount;
  /// Number of distinct field values.
  int cardinal;
  /// Sort indicator.
  /// The default value is no sorting.
  /// This parameter is optional.
  /// 
  /// One of:
  /// * N or NX_SORT_INDICATE_NONE
  /// * A or NX_SORT_INDICATE_ASC
  /// * D or NX_SORT_INDICATE_DESC
  String sortIndicator;
  /// Format of the field.
  /// This parameter is optional.
  FieldAttributes numFormat;
  /// Lowest value in the range.
  num min;
  /// Highest value in the range.
  num max;
  /// This parameter is optional.
  /// Gives information on the error.
  NxValidationError error;
  /// If set to true, it inverts the sort criteria in the field.
  bool reverseSort;
  /// This parameter is set to true if _qNumFormat_ is set to _U_ (unknown). The engine guesses the type of the field based on the field's expression.
  bool isAutoFormat;
  /// List of attribute expressions.
  List<NxAttrExprInfo> attrExprInfo;
  /// List of attribute dimensions.
  List<NxAttrDimInfo> attrDimInfo;
  /// The message displayed if calculation condition is not fulfilled.
  String calcCondMsg;
}

