/// This file was autogenerated

library nx_pivot_page;

import 'package:built_value/serializer.dart';
import 'package:built_value/built_value.dart';
import 'nx_cell.dart';
import 'package:built_collection/built_collection.dart';
import 'rect.dart';
part 'nx_pivot_page.g.dart';

abstract class NxPivotPage implements Built<NxPivotPage, NxPivotPageBuilder> {

 static Serializer<NxPivotPage> get serializer => _$nxPivotPageSerializer;

  /// Information about the left dimension values of a pivot table.
  /// Original name: qLeft
  @nullable
  BuiltList<NxCell> get left;

  /// Information about the top dimension values of a pivot table. If there is no top dimension in the pivot table, information about the measures are given.
  /// Original name: qTop
  @nullable
  BuiltList<NxCell> get top;

  /// Array of data.
  /// Original name: qData
  @nullable
  BuiltList<NxCell> get data;

  /// Size and offset of the data in the matrix.
  /// Original name: qArea
  @nullable
  Rect get area;

  factory NxPivotPage([updates(NxPivotPageBuilder b)]) = _$NxPivotPage;

  NxPivotPage._();
}
