/// This code was autogenerated
import 'package:built_value/built_value.dart';
import 'nx_pivot_dimension_cell.dart';
import 'rect.dart';

class NxPivotPage {
  /// Information about the left dimension values of a pivot table.
  /// Original name: qLeft
  null left;
  /// Information about the top dimension values of a pivot table. If there is no top dimension in the pivot table, information about the measures are given.
  /// Original name: qTop
  null top;
  /// Array of data.
  /// Original name: qData
  NOT_FOUND data;
  /// Size and offset of the data in the matrix.
  /// Original name: qArea
  Rect area;
}

