/// This file was autogenerated

library nx_page_tree_level;

import 'package:built_value/serializer.dart';
import 'package:built_value/built_value.dart';
part 'nx_page_tree_level.g.dart';

abstract class NxPageTreeLevel implements Built<NxPageTreeLevel, NxPageTreeLevelBuilder> {

 static Serializer<NxPageTreeLevel> get serializer => _$nxPageTreeLevelSerializer;

  /// The first dimension that is to be part of the tree, counted from the left. For example, if qLeft is equal to 1, omit nodes from the first dimension in the current sort order.
  /// Original name: qLeft
  @nullable
  int get left;

  /// Number of dimensions to include in the tree.
  /// Original name: qDepth
  @nullable
  int get depth;

  factory NxPageTreeLevel([updates(NxPageTreeLevelBuilder b)]) = _$NxPageTreeLevel;

  NxPageTreeLevel._();
}
