/// This code was autogenerated
import 'package:built_value/built_value.dart';


class NxPageTreeLevel {
  /// The first dimension that is to be part of the tree, counted from the left. For example, if qLeft is equal to 1, omit nodes from the first dimension in the current sort order.
  int left;
  /// Number of dimensions to include in the tree.
  int depth;
}

