/// This code was autogenerated
import 'package:built_value/built_value.dart';
import 'range.dart';

class NxRangeSelectInfo {
  /// Range of values.
  /// Original name: qRange
  Range range;
  /// Number of the measure to select.
  /// Numbering starts from 0.
  /// Original name: qMeasureIx
  int measureIx;
}

