/// This file was autogenerated

library nx_range;

import 'package:built_value/serializer.dart';
import 'package:built_value/built_value.dart';
part 'nx_range.g.dart';

abstract class NxRange implements Built<NxRange, NxRangeBuilder> {

 static Serializer<NxRange> get serializer => _$nxRangeSerializer;

  /// Position in the expression of the first character of the field name.
  /// Original name: qFrom
  @nullable
  int get from;

  /// Number of characters in the field name.
  /// Original name: qCount
  @nullable
  int get count;

  factory NxRange([updates(NxRangeBuilder b)]) = _$NxRange;

  factory NxRange.init({int from, int count}) = _$NxRange._;

  NxRange._();
}
