/// This file was autogenerated

library nx_selection_info;

import 'package:built_value/serializer.dart';
import 'package:built_value/built_value.dart';
part 'nx_selection_info.g.dart';

abstract class NxSelectionInfo implements Built<NxSelectionInfo, NxSelectionInfoBuilder> {

 static Serializer<NxSelectionInfo> get serializer => _$nxSelectionInfoSerializer;

  /// Is set to true if the visualization is in selection mode.
  /// For more information about the selection mode, see _BeginSelections Method_.
  /// Original name: qInSelections
  @nullable
  bool get inSelections;

  /// Is set to true if the visualization is in selection mode and if some selections have been made while in selection mode.
  /// For more information about the selection mode, see _BeginSelections Method_.
  /// Original name: qMadeSelections
  @nullable
  bool get madeSelections;

  factory NxSelectionInfo([updates(NxSelectionInfoBuilder b)]) = _$NxSelectionInfo;

  NxSelectionInfo._();
}
