/// This code was autogenerated
import 'package:built_value/built_value.dart';


class NxSimpleDimValue {
  /// Text related to the attribute expression value.
  /// This property is optional. No text is returned if the attribute expression value is a numeric.
  /// Original name: qText
  String text;
  /// Element number.
  /// Original name: qElemNo
  int elemNo;
}

