/// This code was autogenerated
import 'package:built_value/built_value.dart';


class NxSimpleValue {
  /// Text related to the attribute expression value.
  String text;
  /// Numeric value of the attribute expression.
  /// Set to NaN (Not a Number) if the attribute expression value is not numeric.
  num num;
}

