/// This code was autogenerated
import 'package:built_value/built_value.dart';
import 'nx_stacked_pivot_cell.dart';
import 'rect.dart';

class NxStackPage {
  /// Array of data.
  /// Original name: qData
  null data;
  /// Size and offset of the data in the matrix.
  /// Original name: qArea
  Rect area;
}

