/// This code was autogenerated
import 'package:built_value/built_value.dart';
import 'nx_attribute_expression_values.dart';
import 'nx_attribute_dim_values.dart';

/// Represents a measure.
class NxTreeValue {
  /// The text version of the value, if available.
  String text;
  /// Value of the cell.
  /// Is set to _NaN_ , if the value is not a number.
  num value;
  /// Attribute expression values.
  NxAttributeExpressionValues attrExps;
  /// Attribute dimension values.
  NxAttributeDimValues attrDims;
}

