/// This code was autogenerated
import 'package:built_value/built_value.dart';
import 'nx_tree_value.dart';
import 'nx_tree_node.dart';
import 'nx_attribute_expression_values.dart';
import 'nx_attribute_dim_values.dart';

/// Represents a dimension in the tree.
class NxTreeNode {
  /// The text version of the value, if available.
  String text;
  /// Element number.
  int elemNo;
  /// A generated number applicable to this page only. Used so that children can easily identify who their parents are.
  int nodeNr;
  /// The qNodeNr of this node's parent for the current page.
  int parentNode;
  /// Row index in the data matrix.
  /// The indexing starts from 0.
  int row;
  /// Type of the cell.
  /// 
  /// One of:
  /// * V or NX_DIM_CELL_VALUE
  /// * E or NX_DIM_CELL_EMPTY
  /// * N or NX_DIM_CELL_NORMAL
  /// * T or NX_DIM_CELL_TOTAL
  /// * O or NX_DIM_CELL_OTHER
  /// * A or NX_DIM_CELL_AGGR
  /// * P or NX_DIM_CELL_PSEUDO
  /// * R or NX_DIM_CELL_ROOT
  /// * U or NX_DIM_CELL_NULL
  /// * G or NX_DIM_CELL_GENERATED
  String type;
  /// The measures for this node.
  List<NxTreeValue> values;
  /// The children of this node in the tree structure.
  List<NxTreeNode> nodes;
  /// Attribute expression values.
  NxAttributeExpressionValues attrExps;
  /// Attribute dimension values.
  NxAttributeDimValues attrDims;
}

