/// This code was autogenerated
//import 'package:built_value/built_value.dart';
import 'nx_cell.dart';
import 'nx_page_tree_level.dart';

/// Specifies all the paging filters needed to define the tree to be fetched.
class NxTreeDataOption {
  /// Maximum number of nodes in the tree. If this limit is exceeded, no nodes are returned. All nodes are counted.
  /// Original name: qMaxNbrOfNodes
  int maxNbrOfNodes;
  /// Defines areas of the tree to be fetched. Areas must be defined left to right.
  /// Original name: qTreeNodes
  List<NxCell> treeNodes;
  /// Filters out complete dimensions from the fetched tree.
  /// Original name: qTreeLevels
  NxPageTreeLevel treeLevels;
}

