/// This code was autogenerated
import 'package:built_value/built_value.dart';
import 'range.dart';

class NxTreeRangeSelectInfo {
  /// Range of values.
  Range range;
  /// Number of the measure to select.
  /// Numbering starts from 0.
  int measureIx;
  /// Number of the dimension to select
  /// measure from.  Numbering starts from 0.
  int dimensionIx;
}

