/// This file was autogenerated

library point;

import 'package:built_value/serializer.dart';
import 'package:built_value/built_value.dart';
part 'point.g.dart';

abstract class Point implements Built<Point, PointBuilder> {

 static Serializer<Point> get serializer => _$pointSerializer;

  /// x-coordinate in pixels.
  /// The origin is the top left of the screen.
  /// Original name: qx
  @nullable
  int get x;

  /// y-coordinate in pixels.
  /// The origin is the top left of the screen.
  /// Original name: qy
  @nullable
  int get y;

  factory Point([updates(PointBuilder b)]) = _$Point;

  factory Point.init({int x, int y}) = _$Point._;

  Point._();
}
