/// This code was autogenerated
//import 'package:built_value/built_value.dart';
import 'nx_cell.dart';

class ProgressMessage {
  /// Code number to the corresponding localized message string.
  /// Original name: qMessageCode
  int messageCode;
  /// Parameters to be inserted in the localized message string.
  /// Original name: qMessageParameters
  List<NxCell> messageParameters;
}

