/// This code was autogenerated
import 'package:built_value/built_value.dart';


class RangeSelectInfo {
  /// Lowest value in the range.
  num rangeLo;
  /// Highest value in the range.
  num rangeHi;
  /// Label of the measure.
  String measure;
}

