/// This file was autogenerated

library search_attribute;

import 'package:built_value/serializer.dart';
import 'package:built_value/built_value.dart';
part 'search_attribute.g.dart';

abstract class SearchAttribute
    implements Built<SearchAttribute, SearchAttributeBuilder> {
  static Serializer<SearchAttribute> get serializer =>
      _$searchAttributeSerializer;

  /// String corresponding to _SearchObjectOptions.qAttributes_. It will be _qProperty_ for _SearchObjectOptions_.
  /// Original name: qKey
  @nullable
  String get key;

  /// String corresponding to _qKey_ for the current _SearchGroupItemMatch_. For example, if the match is _Make by Price_ found in the title of a generic object, _qValue_ will be _qMetaDef/title_.
  /// Original name: qValue
  @nullable
  String get value;

  factory SearchAttribute([updates(SearchAttributeBuilder b)]) =
      _$SearchAttribute;

  factory SearchAttribute.init({String key, String value}) =
      _$SearchAttribute._;

  SearchAttribute._();
}
