/// This code was autogenerated
import 'package:built_value/built_value.dart';
import 'search_term_result.dart';

class SearchFieldDictionary {
  /// Position of the field in the list of fields, starting from 0.
  /// The list of fields is defined in _qResults/qFieldNames_ and contains the search associations.
  int field;
  /// List of the matching values.
  /// The maximum number of values in this list is set by _qMaxNbrFieldMatches_ .
  List<SearchTermResult> result;
}

