/// This code was autogenerated
import 'package:built_value/built_value.dart';
import 'search_group_options.dart';
import 'search_group_item_options.dart';

class SearchPage {
  /// Position from the top, starting from 0.
  /// If the offset is set to 0, the first search result to be returned is at position 0.
  /// Original name: qOffset
  int offset;
  /// Number of search groups to return (in _qSearchGroupArray_ ).
  /// Original name: qCount
  int count;
  /// Maximum number of matching values to return per search result.
  /// The default value is -1; all values are returned.
  /// This property is to be used with the _SearchAssociations method_.
  /// Original name: qMaxNbrFieldMatches
  int maxNbrFieldMatches;
  /// Options of the search groups.
  /// If this property is not set, all values are returned.
  /// This property is to be used with the _SearchResults method_ or the _SearchObjects method_.
  /// Original name: qGroupOptions
  null groupOptions;
  /// Options of the search group items.
  /// If this property is not set, all values are returned.
  /// This property is to be used with the _SearchResults method_ or the _SearchObjects method_.
  /// Original name: qGroupItemOptions
  null groupItemOptions;
}

