/// This code was autogenerated
import 'package:built_value/built_value.dart';
import 'search_group_item_match.dart';

class SearchGroupItem {
  /// Type of the group item.
  /// 
  /// One of:
  /// * Field or FIELD
  /// * GenericObject or GENERIC_OBJECT
  /// Original name: qItemType
  String itemType;
  /// Total number of distinct matches in the search group item.
  /// Original name: qTotalNumberOfMatches
  int totalNumberOfMatches;
  /// Identifier of the item.
  /// It corresponds to:
  /// * The name of the field, if the type of the search group is data set.
  /// * The id of the generic object if the type of the search group is generic object.
  /// Original name: qIdentifier
  String identifier;
  /// List of matches in the search group item.
  /// The group item matches are numbered from the value of _SearchGroupItemOptions.qOffset_ to the value of _SearchGroupItemOptions.qOffset_ \+ _SearchGroupItemOptions.qCount_ .
  /// Original name: qItemMatches
  null itemMatches;
  /// Indexes of the search terms that are included in the group item. These search terms are related to the list of terms defined in _SearchResult.qSearchTerms_ .
  /// Original name: qSearchTermsMatched
  null searchTermsMatched;
}

