/// This code was autogenerated
//import 'package:built_value/built_value.dart';
import 'nx_cell.dart';

class SearchFieldDictionary {
  /// Position of the field in the list of fields, starting from 0.
  /// The list of fields is defined in _qResults/qFieldNames_ and contains the search associations.
  /// Original name: qField
  int field;
  /// List of the matching values.
  /// The maximum number of values in this list is set by _qMaxNbrFieldMatches_ .
  /// Original name: qResult
  List<NxCell> result;
}

