/// This code was autogenerated
import 'package:built_value/built_value.dart';


class SearchCharRange {
  /// Starting position of the match in the search result, starting from 0.
  int charPos;
  /// Length of the match in the search result.
  int charCount;
  /// Position of the term in the list of search terms, starting from 0.
  int term;
}

