/// This code was autogenerated
import 'package:built_value/built_value.dart';


class SourceKeyRecord {
  /// Name of the key field.
  /// Original name: qKeyFields
  null keyFields;
  /// Table the key belongs to.
  /// Original name: qTables
  null tables;
}

