/// This file was autogenerated

library source_key_record;

import 'package:built_value/serializer.dart';
import 'package:built_value/built_value.dart';
import 'nx_cell.dart';
import 'package:built_collection/built_collection.dart';
part 'source_key_record.g.dart';

abstract class SourceKeyRecord implements Built<SourceKeyRecord, SourceKeyRecordBuilder> {

 static Serializer<SourceKeyRecord> get serializer => _$sourceKeyRecordSerializer;

  /// Name of the key field.
  /// Original name: qKeyFields
  @nullable
  BuiltList<NxCell> get keyFields;

  /// Table the key belongs to.
  /// Original name: qTables
  @nullable
  BuiltList<NxCell> get tables;

  factory SourceKeyRecord([updates(SourceKeyRecordBuilder b)]) = _$SourceKeyRecord;

  factory SourceKeyRecord.init({BuiltList<NxCell> keyFields, BuiltList<NxCell> tables}) = _$SourceKeyRecord._;

  SourceKeyRecord._();
}
