/// This code was autogenerated
import 'package:built_value/built_value.dart';


/// <div class=note>In addition, this structure can return dynamic properties.</div>
class StaticContentListItem {
  /// Relative path to the content file. The URL is static.
  /// In Qlik Sense Enterprise, content files located:
  /// * In the _/content/ &lt;content library name&gt;/_ folder are part of a global content library.
  /// * In the _/appcontent/_ folder are part of the app specific library.
  /// The content files are never embedded in the _qvf_ file.
  /// In Qlik Sense Desktop, content files located:
  /// * In the _/content/default/_ folder are outside the qvf file.
  /// * In the _/media/ folder_ are embedded in the qvf file.
  /// Original name: qUrlDef
  String urlDef;
  /// Relative path to the content file. The URL is static.
  /// In Qlik Sense Enterprise, content files located:
  /// * In the _/content/ &lt;content library name&gt;/_ folder are part of a global content library.
  /// * In the _/appcontent/_ folder are part of the app specific library.
  /// The content files are never embedded in the _qvf_ file.
  /// In Qlik Sense Desktop, content files located:
  /// * In the _/content/default/_ folder are outside the qvf file.
  /// * In the _/media/ folder_ are embedded in the qvf file.
  /// Original name: qUrl
  String url;
}

