/// This code was autogenerated
//import 'package:built_value/built_value.dart';
import 'nx_cell.dart';

class StaticContentList {
  /// Information about the list of content files.
  /// Original name: qItems
  List<NxCell> items;
}

