/// This code was autogenerated
//import 'package:built_value/built_value.dart';


/// <div class=note>In addition, this structure can return dynamic properties.</div>
class StaticContentUrl {
  /// Relative path of the thumbnail.
  /// Original name: qUrl
  String url;
}

