/// This code was autogenerated
import 'package:built_value/built_value.dart';
import 'table_view_save_info.dart';
import 'table_view_save_info.dart';

class TableViewCtlSaveInfo {
  /// Internal view mode.
  TableViewSaveInfo internalView;
  /// Source view mode.
  TableViewSaveInfo sourceView;
}

