/// This code was autogenerated
import 'package:built_value/built_value.dart';
import 'nx_cell.dart';

class TableViewSaveInfo {
  /// List of the tables in the database model viewer.
  /// Original name: qTables
  List<NxCell> tables;
  /// List of the broom points in the database model viewer.
  /// Not used in Qlik Sense.
  /// Original name: qBroomPoints
  List<NxCell> broomPoints;
  /// List of connection points in the database model viewer.
  /// Not used in Qlik Sense.
  /// Original name: qConnectionPoints
  List<NxCell> connectionPoints;
  /// Zoom factor in the database model viewer.
  /// The default value is 1.0.
  /// Original name: qZoomFactor
  num zoomFactor;
}

