/// This code was autogenerated
import 'package:built_value/built_value.dart';
import 'point.dart';

class TableViewBroomPointSaveInfo {
  /// Information about the position of the broom point.
  Point pos;
  /// Name of the table.
  String table;
  /// List of fields in the table.
  List<String> fields;
}

