/// This file was autogenerated

library table_view_table_win_save_info;

import 'package:built_value/serializer.dart';
import 'package:built_value/built_value.dart';
import 'rect.dart';
part 'table_view_table_win_save_info.g.dart';

abstract class TableViewTableWinSaveInfo
    implements
        Built<TableViewTableWinSaveInfo, TableViewTableWinSaveInfoBuilder> {
  static Serializer<TableViewTableWinSaveInfo> get serializer =>
      _$tableViewTableWinSaveInfoSerializer;

  /// Information about the position of the table.
  /// Original name: qPos
  @nullable
  Rect get pos;

  /// Table name.
  /// Original name: qCaption
  @nullable
  String get caption;

  factory TableViewTableWinSaveInfo(
          [updates(TableViewTableWinSaveInfoBuilder b)]) =
      _$TableViewTableWinSaveInfo;

  factory TableViewTableWinSaveInfo.init({Rect pos, String caption}) =
      _$TableViewTableWinSaveInfo._;

  TableViewTableWinSaveInfo._();
}
