/// This code was autogenerated
//import 'package:built_value/built_value.dart';
import 'point.dart';
import 'nx_cell.dart';

class TableViewBroomPointSaveInfo {
  /// Information about the position of the broom point.
  /// Original name: qPos
  Point pos;
  /// Name of the table.
  /// Original name: qTable
  String table;
  /// List of fields in the table.
  /// Original name: qFields
  List<NxCell> fields;
}

