/// This code was autogenerated
//import 'package:built_value/built_value.dart';
import 'point.dart';
import 'nx_cell.dart';

class TableViewConnectionPointSaveInfo {
  /// Information about the position of the connection point.
  /// Original name: qPos
  Point pos;
  /// List of the fields in the table.
  /// Original name: qFields
  List<NxCell> fields;
}

