/// This code was autogenerated
import 'package:built_value/built_value.dart';
import 'table_view_table_win_save_info.dart';
import 'table_view_broom_point_save_info.dart';
import 'table_view_connection_point_save_info.dart';

class TableViewSaveInfo {
  /// List of the tables in the database model viewer.
  /// Original name: qTables
  null tables;
  /// List of the broom points in the database model viewer.
  /// Not used in Qlik Sense.
  /// Original name: qBroomPoints
  null broomPoints;
  /// List of connection points in the database model viewer.
  /// Not used in Qlik Sense.
  /// Original name: qConnectionPoints
  null connectionPoints;
  /// Zoom factor in the database model viewer.
  /// The default value is 1.0.
  /// Original name: qZoomFactor
  num zoomFactor;
}

