/// This code was autogenerated
//import 'package:built_value/built_value.dart';
import 'table_view_save_info.dart';

class TableViewCtlSaveInfo {
  /// Internal view mode.
  /// Original name: qInternalView
  TableViewSaveInfo internalView;
  /// Source view mode.
  /// Original name: qSourceView
  TableViewSaveInfo sourceView;
}

