/// This code was autogenerated
//import 'package:built_value/built_value.dart';
import 'nx_cell.dart';

class TableRow {
  /// Array of field values.
  /// Original name: qValue
  List<NxCell> value;
}

