/// This file was autogenerated

library text_macro;

import 'package:built_value/serializer.dart';
import 'package:built_value/built_value.dart';
part 'text_macro.g.dart';

abstract class TextMacro implements Built<TextMacro, TextMacroBuilder> {

 static Serializer<TextMacro> get serializer => _$textMacroSerializer;

  /// Name of the variable.
  /// Original name: qTag
  @nullable
  String get tag;

  /// Order in which the variable was referenced during the script execution.
  /// The same number sequence is used for both _qRefSeqNo_ and _qSetSeqNo_ .
  /// Original name: qRefSeqNo
  @nullable
  int get refSeqNo;

  /// Order in which the variable was updated during the script execution.
  /// The same number sequence is used for both _qRefSeqNo_ and _qSetSeqNo_ .
  /// Original name: qSetSeqNo
  @nullable
  int get setSeqNo;

  /// Variable value.
  /// Original name: qDisplayString
  @nullable
  String get displayString;

  /// Is set to true if the variable is a system variable.
  /// Original name: qIsSystem
  @nullable
  bool get isSystem;

  /// Is set to true if the variable is a reserved variable.
  /// Original name: qIsReserved
  @nullable
  bool get isReserved;

  factory TextMacro([updates(TextMacroBuilder b)]) = _$TextMacro;

  factory TextMacro.init({String tag, int refSeqNo, int setSeqNo, String displayString, bool isSystem, bool isReserved}) = _$TextMacro._;

  TextMacro._();
}
