/// This code was autogenerated
import 'package:built_value/built_value.dart';


class TextMacro {
  /// Name of the variable.
  /// Original name: qTag
  String tag;
  /// Order in which the variable was referenced during the script execution.
  /// The same number sequence is used for both _qRefSeqNo_ and _qSetSeqNo_ .
  /// Original name: qRefSeqNo
  int refSeqNo;
  /// Order in which the variable was updated during the script execution.
  /// The same number sequence is used for both _qRefSeqNo_ and _qSetSeqNo_ .
  /// Original name: qSetSeqNo
  int setSeqNo;
  /// Variable value.
  /// Original name: qDisplayString
  String displayString;
  /// Is set to true if the variable is a system variable.
  /// Original name: qIsSystem
  bool isSystem;
  /// Is set to true if the variable is a reserved variable.
  /// Original name: qIsReserved
  bool isReserved;
}

