/// This file was autogenerated

library undo_info;

import 'package:built_value/serializer.dart';
import 'package:built_value/built_value.dart';
part 'undo_info.g.dart';

/// Displays information about the number of possible undos and redos. Is the layout for _UndoInfoDef_.
abstract class UndoInfo implements Built<UndoInfo, UndoInfoBuilder> {

 static Serializer<UndoInfo> get serializer => _$undoInfoSerializer;

  /// Number of possible undos.
  /// Original name: qUndoCount
  @nullable
  int get undoCount;

  /// Number of possible redos.
  /// Original name: qRedoCount
  @nullable
  int get redoCount;

  factory UndoInfo([updates(UndoInfoBuilder b)]) = _$UndoInfo;

  factory UndoInfo.init({int undoCount, int redoCount}) = _$UndoInfo._;

  UndoInfo._();
}
