/// This file was autogenerated

library value_expression;

import 'package:built_value/serializer.dart';
import 'package:built_value/built_value.dart';
part 'value_expression.g.dart';

/// ### Properties
/// Abbreviated syntax:
/// "qValueExpression":"=&lt;expression&gt;"
/// Extended object syntax:
/// "qValueExpression":{"qExpr":"=&lt;expression&gt;"}
/// Where:
/// * &lt; **expression** &gt; is a string.
///
/// <div class=note>The "=" sign in the value expression is not mandatory. Even if the "=" sign is not given, the expression is evaluated.</div>
/// The expression is evaluated as a numeric.
abstract class ValueExpression
    implements Built<ValueExpression, ValueExpressionBuilder> {
  static Serializer<ValueExpression> get serializer =>
      _$valueExpressionSerializer;

  /// Original name: qExpr
  @nullable
  String get expr;

  factory ValueExpression([updates(ValueExpressionBuilder b)]) =
      _$ValueExpression;

  factory ValueExpression.init({String expr}) = _$ValueExpression._;

  ValueExpression._();
}
