/// This code was autogenerated
import 'package:built_value/built_value.dart';
import 'nx_cell.dart';

/// Lists the variables in an app. Is the layout for _VariableListDef_.
class VariableList {
  /// List of the variables.
  /// Original name: qItems
  List<NxCell> items;
}

