name: enigma 
description: Cross platform client for Qlik Associative Engine
homepage: https://github.com/infovizion/enigma-dart
version: 0.0.7
author: Vadim Tsushko <vadimtsushko@gmail.com>

environment:
  sdk: '>=2.0.0-dev.51.0 <3.0.0'
dependencies:
  path: ^1.5.1
  built_collection: '>=3.1.3'
  built_value: ^6.0.0
  logging: ^0.11.3
  web_socket_channel: ^1.0.7
  stream_channel: ^1.6.8
  tuple: ^1.0.2
dev_dependencies:
  test: ^1.0.0
  recase:
    git:
      url: https://github.com/vadimtsushko/recase.git
  build_runner: ^0.9.0
  built_value_generator: ^6.0.0
  grinder: ^0.8.2
  yaml: any
dependency_overrides:
  code_builder: ^3.1.2
  built_value: ^6.0.0