name: enigma 
description: Cross platform client for Qlik Associative Engine
homepage: https://github.com/infovizion/enigma-dart
version: 0.0.5
author: Vadim Tsushko <vadimtsushko@gmail.com>

environment:
  sdk: '>=2.0.0-dev.51.0 <2.0.0'
dependencies:
  path: ^1.5.1
  built_collection: '>=2.0.0 <4.0.0'
  built_value: ^5.4.3
  logging: ^0.11.3
  web_socket_channel: ^1.0.7
  tuple: ^1.0.2
dev_dependencies:
  test: ^0.12.34
  recase: ^1.0.0
  build_runner: ^0.8.10
  built_value_generator: ^5.5.5
  grinder: ^0.8.2
  yaml: any