/// This file was autogenerated

library char_range;

import 'package:built_value/serializer.dart';
import 'package:built_value/built_value.dart';
part 'char_range.g.dart';

abstract class CharRange implements Built<CharRange, CharRangeBuilder> {
  static Serializer<CharRange> get serializer => _$charRangeSerializer;

  /// Position of the first search occurrence.
  /// Original name: qCharPos
  @nullable
  @BuiltValueField(wireName: 'qCharPos')
  int get charPos;

  /// Number of occurrences found.
  /// Original name: qCharCount
  @nullable
  @BuiltValueField(wireName: 'qCharCount')
  int get charCount;

  factory CharRange([updates(CharRangeBuilder b)]) = _$CharRange;

  factory CharRange.init({int charPos, int charCount}) = _$CharRange._;

  CharRange._();
}
