/// This file was autogenerated

library data_table;

import 'package:built_value/serializer.dart';
import 'package:built_value/built_value.dart';
part 'data_table.g.dart';

abstract class DataTable implements Built<DataTable, DataTableBuilder> {
  static Serializer<DataTable> get serializer => _$dataTableSerializer;

  /// Name of the table.
  /// Original name: qName
  @nullable
  @BuiltValueField(wireName: 'qName')
  String get name;

  /// Type of the table.
  /// For example: Table or View.
  /// Original name: qType
  @nullable
  @BuiltValueField(wireName: 'qType')
  String get type;

  factory DataTable([updates(DataTableBuilder b)]) = _$DataTable;

  factory DataTable.init({String name, String type}) = _$DataTable._;

  DataTable._();
}
