/// This file was autogenerated

library do_reload_ex_params;

import 'package:built_value/serializer.dart';
import 'package:built_value/built_value.dart';
part 'do_reload_ex_params.g.dart';

abstract class DoReloadExParams
    implements Built<DoReloadExParams, DoReloadExParamsBuilder> {
  static Serializer<DoReloadExParams> get serializer =>
      _$doReloadExParamsSerializer;

  /// Original name: qMode
  @nullable
  @BuiltValueField(wireName: 'qMode')
  int get mode;

  /// Original name: qPartial
  @nullable
  @BuiltValueField(wireName: 'qPartial')
  bool get partial;

  /// Original name: qDebug
  @nullable
  @BuiltValueField(wireName: 'qDebug')
  bool get debug;

  factory DoReloadExParams([updates(DoReloadExParamsBuilder b)]) =
      _$DoReloadExParams;

  factory DoReloadExParams.init({int mode, bool partial, bool debug}) =
      _$DoReloadExParams._;

  DoReloadExParams._();
}
