/// This file was autogenerated

library editor_breakpoint;

import 'package:built_value/serializer.dart';
import 'package:built_value/built_value.dart';
part 'editor_breakpoint.g.dart';

abstract class EditorBreakpoint
    implements Built<EditorBreakpoint, EditorBreakpointBuilder> {
  static Serializer<EditorBreakpoint> get serializer =>
      _$editorBreakpointSerializer;

  /// Name of the breakpoint.
  /// Original name: qbufferName
  @nullable
  String get bufferName;

  /// Line number in the script where the breakpoint is set.
  /// Original name: qlineIx
  @nullable
  int get lineIx;

  /// If set to true then the breakpoint is enabled (in use).
  /// Original name: qEnabled
  @nullable
  bool get enabled;

  factory EditorBreakpoint([updates(EditorBreakpointBuilder b)]) =
      _$EditorBreakpoint;

  factory EditorBreakpoint.init({String bufferName, int lineIx, bool enabled}) =
      _$EditorBreakpoint._;

  EditorBreakpoint._();
}
