/// This file was autogenerated

library nx_axis_ticks;

import 'package:built_value/serializer.dart';
import 'package:built_value/built_value.dart';
import 'package:built_collection/built_collection.dart';
import 'nx_tick_cell.dart';
part 'nx_axis_ticks.g.dart';

abstract class NxAxisTicks implements Built<NxAxisTicks, NxAxisTicksBuilder> {
  static Serializer<NxAxisTicks> get serializer => _$nxAxisTicksSerializer;

  /// Name of the derived definition.
  /// Original name: qName
  @nullable
  @BuiltValueField(wireName: 'qName')
  String get name;

  /// List of tags.
  /// Original name: qTags
  @nullable
  @BuiltValueField(wireName: 'qTags')
  BuiltList<String> get tags;

  /// List of ticks.
  /// Original name: qTicks
  @nullable
  @BuiltValueField(wireName: 'qTicks')
  BuiltList<NxTickCell> get ticks;

  factory NxAxisTicks([updates(NxAxisTicksBuilder b)]) = _$NxAxisTicks;

  factory NxAxisTicks.init(
      {String name,
      BuiltList<String> tags,
      BuiltList<NxTickCell> ticks}) = _$NxAxisTicks._;

  NxAxisTicks._();
}
