/// This file was autogenerated

library nx_attr_expr_info;

import 'package:built_value/serializer.dart';
import 'package:built_value/built_value.dart';
part 'nx_attr_expr_info.g.dart';

/// Layout for _NxAttrExprDef_.
abstract class NxAttrExprInfo
    implements Built<NxAttrExprInfo, NxAttrExprInfoBuilder> {
  static Serializer<NxAttrExprInfo> get serializer =>
      _$nxAttrExprInfoSerializer;

  /// Minimum value.
  /// Original name: qMin
  @nullable
  @BuiltValueField(wireName: 'qMin')
  num get min;

  /// Maximum value.
  /// Original name: qMax
  @nullable
  @BuiltValueField(wireName: 'qMax')
  num get max;

  /// Original name: qFallbackTitle
  @nullable
  @BuiltValueField(wireName: 'qFallbackTitle')
  String get fallbackTitle;

  /// String version of the minimum Value.
  /// Original name: qMinText
  @nullable
  @BuiltValueField(wireName: 'qMinText')
  String get minText;

  /// String version of the maximum Value.
  /// Original name: qMaxText
  @nullable
  @BuiltValueField(wireName: 'qMaxText')
  String get maxText;

  factory NxAttrExprInfo([updates(NxAttrExprInfoBuilder b)]) = _$NxAttrExprInfo;

  factory NxAttrExprInfo.init(
      {num min,
      num max,
      String fallbackTitle,
      String minText,
      String maxText}) = _$NxAttrExprInfo._;

  NxAttrExprInfo._();
}
