/// This file was autogenerated

library nx_continuous_data_options;

import 'package:built_value/serializer.dart';
import 'package:built_value/built_value.dart';
part 'nx_continuous_data_options.g.dart';

abstract class NxContinuousDataOptions
    implements Built<NxContinuousDataOptions, NxContinuousDataOptionsBuilder> {
  static Serializer<NxContinuousDataOptions> get serializer =>
      _$nxContinuousDataOptionsSerializer;

  /// Start value.
  /// Original name: qStart
  @nullable
  @BuiltValueField(wireName: 'qStart')
  num get start;

  /// End value.
  /// Original name: qEnd
  @nullable
  @BuiltValueField(wireName: 'qEnd')
  num get end;

  /// Number of bins for binning.
  /// Original name: qNbrPoints
  @nullable
  @BuiltValueField(wireName: 'qNbrPoints')
  int get nbrPoints;

  /// Maximum number of ticks.
  /// Original name: qMaxNbrTicks
  @nullable
  @BuiltValueField(wireName: 'qMaxNbrTicks')
  int get maxNbrTicks;

  /// Maximum number of lines.
  /// Original name: qMaxNumberLines
  @nullable
  @BuiltValueField(wireName: 'qMaxNumberLines')
  int get maxNumberLines;

  factory NxContinuousDataOptions([updates(NxContinuousDataOptionsBuilder b)]) =
      _$NxContinuousDataOptions;

  factory NxContinuousDataOptions.init(
      {num start,
      num end,
      int nbrPoints,
      int maxNbrTicks,
      int maxNumberLines}) = _$NxContinuousDataOptions._;

  NxContinuousDataOptions._();
}
