/// This file was autogenerated

library nx_derived_fields_data;

import 'package:built_value/serializer.dart';
import 'package:built_value/built_value.dart';
import 'nx_cell.dart';
import 'package:built_collection/built_collection.dart';
part 'nx_derived_fields_data.g.dart';

abstract class NxDerivedFieldsData
    implements Built<NxDerivedFieldsData, NxDerivedFieldsDataBuilder> {
  static Serializer<NxDerivedFieldsData> get serializer =>
      _$nxDerivedFieldsDataSerializer;

  /// Name of the derived definition.
  /// Original name: qDerivedDefinitionName
  @nullable
  @BuiltValueField(wireName: 'qDerivedDefinitionName')
  String get derivedDefinitionName;

  /// List of the derived fields.
  /// Original name: qFieldDefs
  @nullable
  @BuiltValueField(wireName: 'qFieldDefs')
  BuiltList<NxCell> get fieldDefs;

  /// List of the derived groups.
  /// Original name: qGroupDefs
  @nullable
  @BuiltValueField(wireName: 'qGroupDefs')
  BuiltList<NxCell> get groupDefs;

  /// List of tags on the derived fields.
  /// Original name: qTags
  @nullable
  @BuiltValueField(wireName: 'qTags')
  BuiltList<NxCell> get tags;

  factory NxDerivedFieldsData([updates(NxDerivedFieldsDataBuilder b)]) =
      _$NxDerivedFieldsData;

  factory NxDerivedFieldsData.init(
      {String derivedDefinitionName,
      BuiltList<NxCell> fieldDefs,
      BuiltList<NxCell> groupDefs,
      BuiltList<NxCell> tags}) = _$NxDerivedFieldsData._;

  NxDerivedFieldsData._();
}
