/// This file was autogenerated

library nx_library_measure;

import 'package:built_value/serializer.dart';
import 'package:built_value/built_value.dart';
import 'package:built_collection/built_collection.dart';
part 'nx_library_measure.g.dart';

abstract class NxLibraryMeasure
    implements Built<NxLibraryMeasure, NxLibraryMeasureBuilder> {
  static Serializer<NxLibraryMeasure> get serializer =>
      _$nxLibraryMeasureSerializer;

  /// Original name: qLabel
  @nullable
  @BuiltValueField(wireName: 'qLabel')
  String get label;

  /// Original name: qDef
  @nullable
  @BuiltValueField(wireName: 'qDef')
  String get def;

  ///
  /// One of:
  /// * N or GRP_NX_NONE
  /// * H or GRP_NX_HIEARCHY
  /// * C or GRP_NX_COLLECTION
  /// Original name: qGrouping
  @nullable
  @BuiltValueField(wireName: 'qGrouping')
  String get grouping;

  /// Original name: qExpressions
  @nullable
  @BuiltValueField(wireName: 'qExpressions')
  BuiltList<String> get expressions;

  /// Original name: qActiveExpression
  @nullable
  @BuiltValueField(wireName: 'qActiveExpression')
  int get activeExpression;

  /// Original name: qLabelExpression
  @nullable
  @BuiltValueField(wireName: 'qLabelExpression')
  String get labelExpression;

  factory NxLibraryMeasure([updates(NxLibraryMeasureBuilder b)]) =
      _$NxLibraryMeasure;

  factory NxLibraryMeasure.init(
      {String label,
      String def,
      String grouping,
      BuiltList<String> expressions,
      int activeExpression,
      String labelExpression}) = _$NxLibraryMeasure._;

  NxLibraryMeasure._();
}
