/// This file was autogenerated

library nx_pivot_value_point;

import 'package:built_value/serializer.dart';
import 'package:built_value/built_value.dart';
import 'nx_attribute_expression_values.dart';
import 'nx_attribute_dim_values.dart';
part 'nx_pivot_value_point.g.dart';

abstract class NxPivotValuePoint
    implements Built<NxPivotValuePoint, NxPivotValuePointBuilder> {
  static Serializer<NxPivotValuePoint> get serializer =>
      _$nxPivotValuePointSerializer;

  /// Label of the cell.
  /// This parameter is optional.
  /// Original name: qLabel
  @nullable
  @BuiltValueField(wireName: 'qLabel')
  String get label;

  /// Some text related to the cell.
  /// Original name: qText
  @nullable
  @BuiltValueField(wireName: 'qText')
  String get text;

  /// Value of the cell.
  /// Original name: qNum
  @nullable
  @BuiltValueField(wireName: 'qNum')
  num get qNum;

  /// Type of the cell.
  ///
  /// One of:
  /// * V or NX_DIM_CELL_VALUE
  /// * E or NX_DIM_CELL_EMPTY
  /// * N or NX_DIM_CELL_NORMAL
  /// * T or NX_DIM_CELL_TOTAL
  /// * O or NX_DIM_CELL_OTHER
  /// * A or NX_DIM_CELL_AGGR
  /// * P or NX_DIM_CELL_PSEUDO
  /// * R or NX_DIM_CELL_ROOT
  /// * U or NX_DIM_CELL_NULL
  /// * G or NX_DIM_CELL_GENERATED
  /// Original name: qType
  @nullable
  @BuiltValueField(wireName: 'qType')
  String get type;

  /// Attribute expressions values.
  /// Original name: qAttrExps
  @nullable
  @BuiltValueField(wireName: 'qAttrExps')
  NxAttributeExpressionValues get attrExps;

  /// Original name: qAttrDims
  @nullable
  @BuiltValueField(wireName: 'qAttrDims')
  NxAttributeDimValues get attrDims;

  factory NxPivotValuePoint([updates(NxPivotValuePointBuilder b)]) =
      _$NxPivotValuePoint;

  factory NxPivotValuePoint.init(
      {String label,
      String text,
      num qNum,
      String type,
      NxAttributeExpressionValues attrExps,
      NxAttributeDimValues attrDims}) = _$NxPivotValuePoint._;

  NxPivotValuePoint._();
}
