/// This file was autogenerated

library nx_stack_page;

import 'package:built_value/serializer.dart';
import 'package:built_value/built_value.dart';
import 'nx_stacked_pivot_cell.dart';
import 'package:built_collection/built_collection.dart';
import 'rect.dart';
part 'nx_stack_page.g.dart';

abstract class NxStackPage implements Built<NxStackPage, NxStackPageBuilder> {
  static Serializer<NxStackPage> get serializer => _$nxStackPageSerializer;

  /// Array of data.
  /// Original name: qData
  @nullable
  @BuiltValueField(wireName: 'qData')
  BuiltList<NxStackedPivotCell> get data;

  /// Size and offset of the data in the matrix.
  /// Original name: qArea
  @nullable
  @BuiltValueField(wireName: 'qArea')
  Rect get area;

  factory NxStackPage([updates(NxStackPageBuilder b)]) = _$NxStackPage;

  factory NxStackPage.init({BuiltList<NxStackedPivotCell> data, Rect area}) =
      _$NxStackPage._;

  NxStackPage._();
}
