/// This file was autogenerated

library odbc_dsn;

import 'package:built_value/serializer.dart';
import 'package:built_value/built_value.dart';
part 'odbc_dsn.g.dart';

abstract class OdbcDsn implements Built<OdbcDsn, OdbcDsnBuilder> {
  static Serializer<OdbcDsn> get serializer => _$odbcDsnSerializer;

  /// Name of the ODBC connection.
  /// Original name: qName
  @nullable
  String get name;

  /// Description of the ODBC connection.
  /// Original name: qDescription
  @nullable
  String get description;

  /// Is set to true if the version of ODBC is 32-bit.
  /// This parameter is optional. Default is false.
  /// Original name: qBit32
  @nullable
  bool get bit32;

  /// Is set to true if the connection is User DSN. The connection works only for a specific user.
  /// Default is false.
  /// This parameter is optional.
  /// Original name: qUserOnly
  @nullable
  bool get userOnly;

  factory OdbcDsn([updates(OdbcDsnBuilder b)]) = _$OdbcDsn;

  factory OdbcDsn.init(
      {String name,
      String description,
      bool bit32,
      bool userOnly}) = _$OdbcDsn._;

  OdbcDsn._();
}
