/// This file was autogenerated

library progress_message;

import 'package:built_value/serializer.dart';
import 'package:built_value/built_value.dart';
import 'package:built_collection/built_collection.dart';
part 'progress_message.g.dart';

abstract class ProgressMessage
    implements Built<ProgressMessage, ProgressMessageBuilder> {
  static Serializer<ProgressMessage> get serializer =>
      _$progressMessageSerializer;

  /// Code number to the corresponding localized message string.
  /// Original name: qMessageCode
  @nullable
  @BuiltValueField(wireName: 'qMessageCode')
  int get messageCode;

  /// Parameters to be inserted in the localized message string.
  /// Original name: qMessageParameters
  @nullable
  @BuiltValueField(wireName: 'qMessageParameters')
  BuiltList<String> get messageParameters;

  factory ProgressMessage([updates(ProgressMessageBuilder b)]) =
      _$ProgressMessage;

  factory ProgressMessage.init(
      {int messageCode,
      BuiltList<String> messageParameters}) = _$ProgressMessage._;

  ProgressMessage._();
}
