/// This file was autogenerated

library search_match_combination;

import 'package:built_value/serializer.dart';
import 'package:built_value/built_value.dart';
import 'search_field_match.dart';
import 'package:built_collection/built_collection.dart';
part 'search_match_combination.g.dart';

abstract class SearchMatchCombination
    implements Built<SearchMatchCombination, SearchMatchCombinationBuilder> {
  static Serializer<SearchMatchCombination> get serializer =>
      _$searchMatchCombinationSerializer;

  /// Index of the search result, starting from 0.
  /// Original name: qId
  @nullable
  @BuiltValueField(wireName: 'qId')
  int get id;

  /// Information about the search matches.
  /// Original name: qFieldMatches
  @nullable
  @BuiltValueField(wireName: 'qFieldMatches')
  BuiltList<SearchFieldMatch> get fieldMatches;

  factory SearchMatchCombination([updates(SearchMatchCombinationBuilder b)]) =
      _$SearchMatchCombination;

  factory SearchMatchCombination.init(
      {int id,
      BuiltList<SearchFieldMatch> fieldMatches}) = _$SearchMatchCombination._;

  SearchMatchCombination._();
}
