/// This file was autogenerated

library selection_object_def;

import 'package:built_value/serializer.dart';
import 'package:built_value/built_value.dart';
part 'selection_object_def.g.dart';

/// To display the current selections.
/// Can be added to any generic object but is particularly meaningful when using session objects to monitor an app.
///
/// ### Properties
/// "qSelectionObjectDef": {}
abstract class SelectionObjectDef
    implements Built<SelectionObjectDef, SelectionObjectDefBuilder> {
  static Serializer<SelectionObjectDef> get serializer =>
      _$selectionObjectDefSerializer;

  /// Original name: qStateName
  @nullable
  @BuiltValueField(wireName: 'qStateName')
  String get stateName;

  factory SelectionObjectDef([updates(SelectionObjectDefBuilder b)]) =
      _$SelectionObjectDef;

  factory SelectionObjectDef.init({String stateName}) = _$SelectionObjectDef._;

  SelectionObjectDef._();
}
