/// This file was autogenerated

library table_row;

import 'package:built_value/serializer.dart';
import 'package:built_value/built_value.dart';
import 'field_value.dart';
import 'package:built_collection/built_collection.dart';
part 'table_row.g.dart';

abstract class TableRow implements Built<TableRow, TableRowBuilder> {
  static Serializer<TableRow> get serializer => _$tableRowSerializer;

  /// Array of field values.
  /// Original name: qValue
  @nullable
  @BuiltValueField(wireName: 'qValue')
  BuiltList<FieldValue> get value;

  factory TableRow([updates(TableRowBuilder b)]) = _$TableRow;

  factory TableRow.init({BuiltList<FieldValue> value}) = _$TableRow._;

  TableRow._();
}
