/// This file was autogenerated

library table_view_ctl_save_info;

import 'package:built_value/serializer.dart';
import 'package:built_value/built_value.dart';
import 'table_view_save_info.dart';
part 'table_view_ctl_save_info.g.dart';

abstract class TableViewCtlSaveInfo
    implements Built<TableViewCtlSaveInfo, TableViewCtlSaveInfoBuilder> {
  static Serializer<TableViewCtlSaveInfo> get serializer =>
      _$tableViewCtlSaveInfoSerializer;

  /// Internal view mode.
  /// Original name: qInternalView
  @nullable
  @BuiltValueField(wireName: 'qInternalView')
  TableViewSaveInfo get internalView;

  /// Source view mode.
  /// Original name: qSourceView
  @nullable
  @BuiltValueField(wireName: 'qSourceView')
  TableViewSaveInfo get sourceView;

  factory TableViewCtlSaveInfo([updates(TableViewCtlSaveInfoBuilder b)]) =
      _$TableViewCtlSaveInfo;

  factory TableViewCtlSaveInfo.init(
      {TableViewSaveInfo internalView,
      TableViewSaveInfo sourceView}) = _$TableViewCtlSaveInfo._;

  TableViewCtlSaveInfo._();
}
