/// This file was autogenerated

library table_view_save_info;

import 'package:built_value/serializer.dart';
import 'package:built_value/built_value.dart';
import 'table_view_table_win_save_info.dart';
import 'package:built_collection/built_collection.dart';
import 'table_view_broom_point_save_info.dart';
import 'table_view_connection_point_save_info.dart';
part 'table_view_save_info.g.dart';

abstract class TableViewSaveInfo
    implements Built<TableViewSaveInfo, TableViewSaveInfoBuilder> {
  static Serializer<TableViewSaveInfo> get serializer =>
      _$tableViewSaveInfoSerializer;

  /// List of the tables in the database model viewer.
  /// Original name: qTables
  @nullable
  @BuiltValueField(wireName: 'qTables')
  BuiltList<TableViewTableWinSaveInfo> get tables;

  /// List of the broom points in the database model viewer.
  /// Not used in Qlik Sense.
  /// Original name: qBroomPoints
  @nullable
  @BuiltValueField(wireName: 'qBroomPoints')
  BuiltList<TableViewBroomPointSaveInfo> get broomPoints;

  /// List of connection points in the database model viewer.
  /// Not used in Qlik Sense.
  /// Original name: qConnectionPoints
  @nullable
  @BuiltValueField(wireName: 'qConnectionPoints')
  BuiltList<TableViewConnectionPointSaveInfo> get connectionPoints;

  /// Zoom factor in the database model viewer.
  /// The default value is 1.0.
  /// Original name: qZoomFactor
  @nullable
  @BuiltValueField(wireName: 'qZoomFactor')
  num get zoomFactor;

  factory TableViewSaveInfo([updates(TableViewSaveInfoBuilder b)]) =
      _$TableViewSaveInfo;

  factory TableViewSaveInfo.init(
      {BuiltList<TableViewTableWinSaveInfo> tables,
      BuiltList<TableViewBroomPointSaveInfo> broomPoints,
      BuiltList<TableViewConnectionPointSaveInfo> connectionPoints,
      num zoomFactor}) = _$TableViewSaveInfo._;

  TableViewSaveInfo._();
}
