/// This code was autogenerated
import 'package:built_value/built_value.dart';
import 'nx_meta.dart';

class AppScript {
  /// Script text.
  String script;
  /// Information about publishing and permissions.
  /// This parameter is optional.
  NxMeta meta;
}

