/// This code was autogenerated
import 'package:built_value/built_value.dart';


class CharRange {
  /// Position of the first search occurrence.
  int charPos;
  /// Number of occurrences found.
  int charCount;
}

