/// This code was autogenerated
import 'package:built_value/built_value.dart';


class CodePage {
  /// Number of the code page.
  int number;
  /// Name of the code page.
  String name;
  /// Description of the code page.
  String description;
}

