/// This code was autogenerated
import 'package:built_value/built_value.dart';
import 'data_field.dart';

class DataTableEx {
  /// Name of the table.
  String name;
  /// List of the fields in the table.
  List<DataField> fields;
  /// List of format specification items, within brackets.
  /// Examples of specification items:
  /// * file type
  /// * embedded labels, no labels
  /// * table is &lt;table name&gt;
  String formatSpec;
}

