/// This code was autogenerated
import 'package:built_value/built_value.dart';


class FieldDefEx {
  /// Name of the field.
  String name;
  /// Type of data entity.
  /// 
  /// One of:
  /// * NOT_PRESENT
  /// * PRESENT
  /// * IS_CYCLIC_GROUP
  /// * IS_DRILL_GROUP
  /// * IS_VAR
  /// * IS_EXPR
  /// * IS_IMPLICIT
  /// * IS_DETAIL
  String type;
}

