/// This code was autogenerated
import 'package:built_value/built_value.dart';


class FilterInfo {
  /// 
  /// One of:
  /// * NONE or FILTER_TYPE_NONE
  /// * RAW or FILTER_TYPE_RAW
  String type;
  String wherePredicate;
}

