/// This code was autogenerated
import 'package:built_value/built_value.dart';


class FolderItem {
  /// Name of the folder item.
  String name;
  /// Type of the folder item.
  /// 
  /// One of:
  /// * FOLDER or FOLDER_ITEM_FOLDER
  /// * FILE or FOLDER_ITEM_FILE
  /// * OTHER or FOLDER_ITEM_OTHER
  String type;
}

