/// This code was autogenerated
import 'package:built_value/built_value.dart';
import 'generic_object_properties.dart';
import 'generic_object_entry.dart';
import 'generic_bookmark_entry.dart';

class GenericObjectEntry {
  /// Information about the generic object properties.
  GenericObjectProperties property;
  /// Information about the children of the generic object.
  List<GenericObjectEntry> children;
  /// Reference to a bookmark/snapshot that is embedded in the generic object.
  GenericBookmarkEntry embeddedSnapshotRef;
}

