/// This code was autogenerated
import 'package:built_value/built_value.dart';
import 'nx_info.dart';
import 'nx_library_measure.dart';
import 'nx_meta.dart';

/// Is the layout for _GenericMeasureProperties_.
class GenericMeasureLayout {
  /// Information about the object.
  NxInfo info;
  /// Information about the measure.
  NxLibraryMeasure measure;
  /// Information on publishing and permissions.
  NxMeta meta;
}

