/// This code was autogenerated
import 'package:built_value/built_value.dart';
import 'nx_info.dart';
import 'nx_library_dimension_def.dart';
import 'nx_meta_def.dart';

class GenericDimensionProperties {
  /// Identifier and type of the dimension.
  /// This parameter is mandatory.
  NxInfo info;
  /// Definition of the dimension.
  /// This parameter is mandatory.
  NxLibraryDimensionDef dim;
  /// Definition of the dynamic properties.
  NxMetaDef metaDef;
}

