/// This code was autogenerated
import 'package:built_value/built_value.dart';


class InteractDef {
  /// Interaction type.
  /// 
  /// One of:
  /// * IT_MSGBOX
  /// * IT_SCRIPTLINE
  /// * IT_BREAK
  /// * IT_INPUT
  /// * IT_END
  /// * IT_PASSWD
  /// * IT_USERNAME
  String type;
  /// Title used in the message box dialog.
  /// This property is relevant if _qType_ is *IT_MSGBOX*.
  String title;
  /// Message used in the message box dialog.
  /// This property is relevant if _qType_ is *IT_MSGBOX*.
  String msg;
  /// Buttons displayed in the message box dialog.
  /// This property is relevant if _qType_ is *IT_MSGBOX*.
  /// One of:
  /// * 0 means that the _qButtons_ property is not relevant.
  /// * 17 means that the message box contains the **OK** and **Cancel** buttons or the **stop** -sign icon.
  int buttons;
  /// Next script statement to be executed.
  /// This property is used if the type of interaction is *IT_SCRIPTLINE*.
  String line;
  /// First line number of the previously executed statement.
  /// This property is used if the type of interaction is *IT_SCRIPTLINE*.
  int oldLineNr;
  /// First line number of the next statement to be executed.
  /// This property is used if the type of interaction is *IT_SCRIPTLINE*.
  int newLineNr;
  /// Path specified by the **Include** script variable.
  /// This property is used if the type of interaction is *IT_SCRIPTLINE*.
  /// Example of an **Include** variable:
  /// _$(Include=lib:\\\MyDataFiles\abc.txt);_
  String path;
  /// This property is set to true if the returned statement is an hidden script statement.
  bool hidden;
  /// Not relevant for describing the requested user interaction.
  int result;
  /// Is not used in Qlik Sense.
  String input;
}

