/// This code was autogenerated
import 'package:built_value/built_value.dart';
import 'nx_container_entry.dart';

/// Lists the measures. Is the layout for _MeasureListDef_.
class MeasureList {
  /// Information about the list of measures.
  List<NxContainerEntry> items;
}

