/// This code was autogenerated
import 'package:built_value/built_value.dart';
import 'range_select_info.dart';
import 'nx_state_counts.dart';
import 'nx_field_selection_info.dart';
import 'nx_field_selection_info.dart';

class NxCurrentSelectionItem {
  /// Number of values in the field.
  int total;
  /// This parameter is displayed if its value is true.
  /// Is set to true if the field is a numeric.
  /// This parameter is optional.
  bool isNum;
  /// Name of the field that is selected.
  String field;
  /// This parameter is displayed if its value is true.
  /// Is set to true if the field is locked.
  /// This parameter is optional.
  bool locked;
  /// This parameter is displayed if its value is true.
  /// Property that is set to a field. Is set to true if the field cannot be unselected.
  /// This parameter is optional.
  bool oneAndOnlyOne;
  /// Text that was used for the search. This parameter is filled when searching for a value and selecting it.
  /// This parameter is optional.
  String textSearch;
  /// Number of values that are selected.
  int selectedCount;
  /// Values that are selected.
  String selected;
  /// Information about the range of selected values.
  /// Is empty if there is no range of selected values.
  List<RangeSelectInfo> rangeInfo;
  /// Sort index of the field. Indexing starts from 0.
  int sortIndex;
  /// Number of values in a particular state.
  NxStateCounts stateCounts;
  /// Information about the fields that are selected.
  List<NxFieldSelectionInfo> selectedFieldSelectionInfo;
  /// Information about the fields that are not selected.
  List<NxFieldSelectionInfo> notSelectedFieldSelectionInfo;
  /// Maximum values to show in the current selections.
  /// The default value is 6.
  int selectionThreshold;
  /// Label that, if defined, is displayed in current selections instead of the actual expression.
  String readableName;
  /// Optional parameter. Indicates if the selection is to be hidden in the Selections bar.
  /// Is set to true if the current selection is hidden.
  bool isHidden;
}

