/// This code was autogenerated
import 'package:built_value/built_value.dart';
import 'value_expr.dart';
import 'string_expr.dart';

class NxCalcCond {
  /// Condition for calculating an hypercube, dimension or measure.
  ValueExpr cond;
  /// Evaluated if Cond is not fullfilled.
  StringExpr msg;
}

