/// This code was autogenerated
import 'package:built_value/built_value.dart';


class NxDerivedField {
  /// Identifier of the derived field.
  /// The identifier is unique.
  String id;
  /// Combination of field name, definition and method.
  /// Example:
  /// _OrderDate.MyDefinition.Year_
  String name;
  /// Method name associated to the derived field.
  String method;
  /// Expression of the derived field.
  /// Example:
  /// If _qName_ is _OrderDate.MyDefinition.Year_ , the expression is as follows:
  /// _=${Mydefinition(OrderDate).Year}_
  String expr;
  /// List of tags.
  List<String> tags;
}

