/// This code was autogenerated
import 'package:built_value/built_value.dart';
import 'nx_state_counts.dart';
import 'nx_validation_error.dart';
import 'field_attributes.dart';
import 'nx_attr_expr_info.dart';
import 'nx_attr_dim_info.dart';

class NxDimensionInfo {
  /// Corresponds to the label of the dimension that is selected.
  /// If the label is not defined then the field name is used.
  String fallbackTitle;
  /// Length of the longest value in the field.
  int apprMaxGlyphCount;
  /// Number of distinct field values.
  int cardinal;
  /// Is set to true if the field is locked.
  bool locked;
  /// Sort indicator.
  /// The default value is no sorting.
  /// This parameter is optional.
  /// 
  /// One of:
  /// * N or NX_SORT_INDICATE_NONE
  /// * A or NX_SORT_INDICATE_ASC
  /// * D or NX_SORT_INDICATE_DESC
  String sortIndicator;
  /// Array of dimension labels.
  /// Contains the labels of all dimensions in a hierarchy group (for example the labels of all dimensions in a drill down group).
  List<String> groupFallbackTitles;
  /// Index of the dimension that is currently in use.
  /// _qGroupPos_ is set to 0 if there are no hierarchical groups (drill-down groups) or cycle groups.
  int groupPos;
  /// Number of values in a particular state.
  NxStateCounts stateCounts;
  /// Gives information on a field. For example, it can return the type of the field.
  /// Examples: key, text, ASCII
  List<String> tags;
  /// This parameter is optional.
  /// Gives information on the error.
  NxValidationError error;
  /// Binary format of the field.
  /// 
  /// One of:
  /// * D or NX_DIMENSION_TYPE_DISCRETE
  /// * N or NX_DIMENSION_TYPE_NUMERIC
  /// * T or NX_DIMENSION_TYPE_TIME
  String dimensionType;
  /// If set to true, it inverts the sort criteria in the field.
  bool reverseSort;
  /// Defines the grouping.
  /// 
  /// One of:
  /// * N or GRP_NX_NONE
  /// * H or GRP_NX_HIEARCHY
  /// * C or GRP_NX_COLLECTION
  String grouping;
  /// If set to true, it means that the field is a semantic.
  bool isSemantic;
  /// If set to true, it means that the field always has one and only one selected value.
  bool isOneAndOnlyOne;
  /// Format of the field.
  /// This parameter is optional.
  FieldAttributes numFormat;
  /// This parameter is set to true if _qNumFormat_ is set to _U_ (unknown). The engine guesses the type of the field based on the field's definition.
  bool isAutoFormat;
  /// Array of field names.
  List<String> groupFieldDefs;
  /// Minimum value.
  num min;
  /// Maximum value.
  num max;
  /// Is continuous axis used.
  bool continuousAxes;
  /// Is a cyclic dimension used.
  bool isCyclic;
  /// Is derived field is used as a dimension.
  bool derivedField;
  /// Array of attribute expressions.
  List<NxAttrExprInfo> attrExprInfo;
  /// Array of attribute dimensions.
  List<NxAttrDimInfo> attrDimInfo;
  /// The message displayed if calculation condition is not fulfilled.
  String calcCondMsg;
  /// True if this is a calculated dimension.
  bool isCalculated;
}

