/// This code was autogenerated
import 'package:built_value/built_value.dart';


class NxFieldSelectionInfo {
  /// Name of the field.
  String name;
  /// Selection mode.
  /// ### Properties
  /// One of:
  /// * NORMAL for a selection in normal mode.
  /// * AND for a selection in AND mode.
  /// * NOT for a selection NOT in AND mode.
  /// One of:
  /// * NORMAL or SELECTION_MODE_NORMAL
  /// * AND or SELECTION_MODE_AND
  /// * NOT or SELECTION_MODE_NOT
  String fieldSelectionMode;
}

