/// This code was autogenerated
import 'package:built_value/built_value.dart';
import 'sort_criteria.dart';
import 'field_attributes.dart';

class NxInlineDimensionDef {
  /// Used to define a cyclic group or drill-down group.
  /// Default value is no grouping.
  /// This parameter is optional.
  /// 
  /// One of:
  /// * N or GRP_NX_NONE
  /// * H or GRP_NX_HIEARCHY
  /// * C or GRP_NX_COLLECTION
  String grouping;
  /// Array of field names.
  /// When creating a grouped dimension, more than one field name is defined.
  /// This parameter is optional.
  List<String> fieldDefs;
  /// Array of field labels.
  /// This parameter is optional.
  List<String> fieldLabels;
  /// Defines the sorting criteria in the field.
  /// Default is to sort by alphabetical order, ascending.
  /// This parameter is optional.
  List<SortCriteria> sortCriterias;
  /// Defines the format of the value.
  /// This parameter is optional.
  List<FieldAttributes> numberPresentations;
  /// If set to true, it inverts the sort criteria in the field.
  bool reverseSort;
  /// Index of the active field in a cyclic dimension.
  /// This parameter is optional. The default value is 0.
  /// This parameter is used in case of cyclic dimensions ( _qGrouping_ is C).
  int activeField;
  /// Label expression.
  /// This parameter is optional.
  String labelExpression;
}

