/// This code was autogenerated
import 'package:built_value/built_value.dart';


class NxLibraryDimensionDef {
  /// Information about the grouping.
  /// 
  /// One of:
  /// * N or GRP_NX_NONE
  /// * H or GRP_NX_HIEARCHY
  /// * C or GRP_NX_COLLECTION
  String grouping;
  /// Array of dimension names.
  List<String> fieldDefs;
  /// Array of dimension labels.
  List<String> fieldLabels;
  String labelExpression;
}

