/// This code was autogenerated
import 'package:built_value/built_value.dart';
import 'nx_range_select_info.dart';

class NxMultiRangeSelectInfo {
  List<NxRangeSelectInfo> ranges;
  List<int> columnsToSelect;
}

