/// This code was autogenerated
import 'package:built_value/built_value.dart';
import 'nx_attribute_expression_values.dart';
import 'nx_attribute_dim_values.dart';

class NxPivotValuePoint {
  /// Label of the cell.
  /// This parameter is optional.
  String label;
  /// Some text related to the cell.
  String text;
  /// Value of the cell.
  num num;
  /// Type of the cell.
  /// 
  /// One of:
  /// * V or NX_DIM_CELL_VALUE
  /// * E or NX_DIM_CELL_EMPTY
  /// * N or NX_DIM_CELL_NORMAL
  /// * T or NX_DIM_CELL_TOTAL
  /// * O or NX_DIM_CELL_OTHER
  /// * A or NX_DIM_CELL_AGGR
  /// * P or NX_DIM_CELL_PSEUDO
  /// * R or NX_DIM_CELL_ROOT
  /// * U or NX_DIM_CELL_NULL
  /// * G or NX_DIM_CELL_GENERATED
  String type;
  /// Attribute expressions values.
  NxAttributeExpressionValues attrExps;
  NxAttributeDimValues attrDims;
}

