/// This code was autogenerated
import 'package:built_value/built_value.dart';
import 'nx_pivot_dimension_cell.dart';
import 'nx_attribute_expression_values.dart';
import 'nx_attribute_dim_values.dart';

class NxPivotDimensionCell {
  /// Some text.
  String text;
  /// Rank number of the value.
  /// If set to -1, it means that the value is not an element number.
  int elemNo;
  /// Value of the cell.
  /// Is set to _NaN_ , if the value is not a number.
  num value;
  /// If set to true, it means that the cell can be expanded.
  /// This parameter is not returned if it is set to false.
  bool canExpand;
  /// If set to true, it means that the cell can be collapsed.
  /// This parameter is not returned if it is set to false.
  bool canCollapse;
  /// Type of the cell.
  /// 
  /// One of:
  /// * V or NX_DIM_CELL_VALUE
  /// * E or NX_DIM_CELL_EMPTY
  /// * N or NX_DIM_CELL_NORMAL
  /// * T or NX_DIM_CELL_TOTAL
  /// * O or NX_DIM_CELL_OTHER
  /// * A or NX_DIM_CELL_AGGR
  /// * P or NX_DIM_CELL_PSEUDO
  /// * R or NX_DIM_CELL_ROOT
  /// * U or NX_DIM_CELL_NULL
  /// * G or NX_DIM_CELL_GENERATED
  String type;
  /// Number of elements that are part of the previous tail.
  /// This number depends on the paging, more particularly it depends on the values defined in _qTop_ and _qHeight_ .
  int up;
  /// Number of elements that are part of the next tail.
  /// This number depends on the paging, more particularly it depends on the values defined in _qTop_ and _qHeight_ .
  int down;
  /// Information about sub nodes (or sub cells).
  /// The array is empty _[ ]_ when there is no sub nodes.
  List<NxPivotDimensionCell> subNodes;
  /// Information about attribute expressions.
  /// The array is empty _[ ]_ when there is no attribute expressions.
  NxAttributeExpressionValues attrExps;
  /// Information about attribute dimensions.
  NxAttributeDimValues attrDims;
}

