/// This code was autogenerated
import 'package:built_value/built_value.dart';


class NxStateCounts {
  /// Number of values in locked state.
  int locked;
  /// Number of values in selected state.
  int selected;
  /// Number of values in optional state.
  int option;
  /// Number of values in deselected state.
  int deselected;
  /// Number of values in alternative state.
  int alternative;
  /// Number of values in excluded state.
  int excluded;
  /// Number of values in selected excluded state.
  int selectedExcluded;
  /// Number of values in locked excluded state.
  int lockedExcluded;
}

