/// This code was autogenerated
import 'package:built_value/built_value.dart';
import 'field_attributes.dart';

class NxVariableProperties {
  /// Name of the variable.
  String name;
  /// Defines the format of the value of a variable.
  FieldAttributes numberPresentation;
  /// Set this property to true to update the variable when applying a bookmark.
  /// The value of a variable can affect the state of the selections.
  /// The default value is false.
  bool includeInBookmark;
  /// The value of a variable can be an enumeration.
  /// Set this property to true to reflect the predefined values in an enumeration.
  bool usePredefListedValues;
  /// List of enumerations.
  /// This property is used if _qUsePredefListedValues_ is set to true.
  List<String> preDefinedList;
}

