/// This code was autogenerated
import 'package:built_value/built_value.dart';


class ScriptSyntaxError {
  /// Length of the word where the error is located.
  int errLen;
  /// Number of the faulty section.
  int tabIx;
  /// Line number in the section where the error is located.
  int lineInTab;
  /// Position of the erroneous text from the beginning of the line.
  int colInLine;
  /// Position of the erroneous text from the beginning of the script.
  int textPos;
  /// The default value is false.
  bool secondaryFailure;
}

