/// This code was autogenerated
import 'package:built_value/built_value.dart';


/// To display the current selections.
/// Can be added to any generic object but is particularly meaningful when using session objects to monitor an app.
/// 
/// ### Properties
/// "qSelectionObjectDef": {}
class SelectionObjectDef {
  String stateName;
}

