/// This code was autogenerated
import 'package:built_value/built_value.dart';
import 'field_in_table_data.dart';
import 'point.dart';

class TableRecord {
  /// Name of the table.
  String name;
  /// This property is set to true if the table is loose.
  bool loose;
  /// Number of rows in the table.
  int noOfRows;
  /// Information about the fields in the table.
  List<FieldInTableData> fields;
  /// Information about the position of the table.
  Point pos;
  /// Comment related to the table.
  String comment;
  /// If set to true, Direct Discovery is used.
  /// Direct Discovery fields are not loaded into memory and remain in the external database.
  bool isDirectDiscovery;
  /// This property is set to true if the table contains a synthetic key.
  bool isSynthetic;
}

