/// This code was autogenerated
import 'package:built_value/built_value.dart';
import 'rect.dart';

class TableViewTableWinSaveInfo {
  /// Information about the position of the table.
  Rect pos;
  /// Table name.
  String caption;
}

