/// This code was autogenerated
import 'package:built_value/built_value.dart';


/// Displays information about the number of possible undos and redos. Is the layout for _UndoInfoDef_.
class UndoInfo {
  /// Number of possible undos.
  int undoCount;
  /// Number of possible redos.
  int redoCount;
}

