/// This code was autogenerated
import 'package:built_value/built_value.dart';


/// ### Properties
/// Abbreviated syntax:
/// "qValueExpression":"=&lt;expression&gt;"
/// Extended object syntax:
/// "qValueExpression":{"qExpr":"=&lt;expression&gt;"}
/// Where:
/// * &lt; **expression** &gt; is a string.
/// 
/// <div class=note>The "=" sign in the value expression is not mandatory. Even if the "=" sign is not given, the expression is evaluated.</div>
/// The expression is evaluated as a numeric.
class ValueExpression {
  String expr;
}

