name: qlient_generator
description: API generator for qlient
version: 0.0.2
author: Vadim Tsushko <vadimtsushko@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'
dependencies:
  path: ^1.5.1
  meta: ^1.0.4
  built_collection: '>=2.0.0 <4.0.0'
  built_value: ^5.4.3
  dart_style: ^1.0.11
  web_socket_channel: ^1.0.7
dev_dependencies:
  test: ^0.12.34
  recase: ^1.0.0
  build_runner: ^0.8.3
  built_value_generator: ^5.4.3