name: qlient_generator
description: API generator for qlient
version: 0.0.3
author: Vadim Tsushko <vadimtsushko@gmail.com>

environment:
  sdk: '>=2.0.0-dev.51.0 <3.0.0'
dependencies:
  path: ^1.5.1
  meta: ^1.0.4
  built_collection: '>=3.1.3'
  built_value: ^6.0.0
  dart_style: ^1.0.11
  web_socket_channel: ^1.0.7
dev_dependencies:
  test: ^1.0.0
  recase:
    git:
      url: https://github.com/vadimtsushko/recase.git
  build_runner: ^0.9.0
  built_value_generator: ^6.0.0
